table FT_OFENSORES_LLM
	lineageTag: c4d812a3-c39e-43fe-92b7-07d4772a9d83

	column 'Nome da Origem'
		dataType: string
		lineageTag: 04e815b8-9593-4c34-a4eb-512b4668b0c7
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column Protocolo
		dataType: string
		lineageTag: bf035d96-a2dc-40ad-87d6-bb178736178d
		summarizeBy: none
		sourceColumn: Protocolo

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: c09b1d4d-38c1-4519-ae89-321f75132a87
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Bloco
		dataType: string
		lineageTag: 0fc4a595-07e1-4f83-9608-663f765e9566
		summarizeBy: none
		sourceColumn: Bloco

		annotation SummarizationSetBy = Automatic

	column TAG
		dataType: string
		lineageTag: 98f42469-f332-41a9-a6ea-f5f83e86d453
		summarizeBy: none
		sourceColumn: TAG

		annotation SummarizationSetBy = Automatic

	column Sub-Item
		dataType: string
		lineageTag: 4e509e4c-1673-40c9-bd7e-2890c43639a4
		summarizeBy: none
		sourceColumn: Sub-Item

		annotation SummarizationSetBy = Automatic

	column NCG
		dataType: string
		lineageTag: 79df3e9a-5adf-472f-a733-f2cd74038eaf
		summarizeBy: none
		sourceColumn: NCG

		annotation SummarizationSetBy = Automatic

	column Diagnóstico
		dataType: string
		lineageTag: e5b3ec27-5fa0-4df7-be63-4fd9b1fb7fd6
		summarizeBy: none
		sourceColumn: Diagnóstico

		annotation SummarizationSetBy = Automatic

	column Peso
		dataType: double
		lineageTag: f072723d-9c37-482d-867b-d4feefb9c681
		summarizeBy: sum
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Apontamento
		dataType: string
		lineageTag: 34406746-3c6a-4f8b-bfe5-a4accef3e62b
		summarizeBy: none
		sourceColumn: Apontamento

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 904adb60-015a-4bd6-a306-95a3e35e4c82
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 8e2d00ad-ca51-41fd-9d2e-c672fa71d7a3
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	partition FT_OFENSORES_LLM = m
		mode: import
		queryGroup: CSAT
		source = ```
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"cd285858-e86a-4854-ae7f-7fbf647a6920" = Workspaces{[workspaceId="cd285858-e86a-4854-ae7f-7fbf647a6920"]}[Data],
				    #"287e2c31-79b7-4f71-8901-c2df7db09ddc" = #"cd285858-e86a-4854-ae7f-7fbf647a6920"{[dataflowId="287e2c31-79b7-4f71-8901-c2df7db09ddc"]}[Data],
				    #"Ft_Apontamentos LLM_" = #"287e2c31-79b7-4f71-8901-c2df7db09ddc"{[entity="Ft_Apontamentos LLM",version=""]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(#"Ft_Apontamentos LLM_", each Text.Contains([Cliente], "COMGÁS") or Text.Contains([Cliente], "Comgás")),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"Name", "Nome da Origem"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Peso", type number}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Cliente", "Monitorado", "Supervisor", "Nome da Ficha"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"Nome da Origem", "TAG", "Item", "Apontamento"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Reordenadas", "Item 2", each if Text.StartsWith([Item], "1.") or Text.StartsWith([Item], "2.") or Text.StartsWith([Item], "3.") then 
				    Text.Middle([Item], 4) 
				else 
				    [Item]),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Personalização Adicionada",{"Item"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"Item 2", "Item"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Item", type text}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Tipo Alterado2", "Índice", 1, 1, Int64.Type),
				    #"Texto Aparado" = Table.TransformColumns(#"Índice Adicionado",{{"Item", Text.Trim, type text}})
				in
				    #"Texto Aparado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

