table FT_QUALIDADE_LLM
	lineageTag: 2c389219-d44f-46fb-8906-110165687e1e

	column Name
		dataType: string
		lineageTag: 0dc38e32-bdde-42aa-b40a-15111e78936f
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Nome do Formulário'
		dataType: string
		lineageTag: 0eaed408-affc-4ff4-b85d-39978c23480a
		summarizeBy: none
		sourceColumn: Nome do Formulário

		annotation SummarizationSetBy = Automatic

	column Agente
		dataType: string
		lineageTag: b16de075-1b17-480a-a3b5-e845769fa484
		summarizeBy: none
		sourceColumn: Agente

		annotation SummarizationSetBy = Automatic

	column Funcional
		dataType: string
		lineageTag: 53b24074-af5f-41a8-96f1-9af2542a2077
		summarizeBy: none
		sourceColumn: Funcional

		annotation SummarizationSetBy = Automatic

	column Supervisor
		dataType: string
		lineageTag: ef85b1cd-f0a7-457a-a07b-89f5776e9f2d
		summarizeBy: none
		sourceColumn: Supervisor

		annotation SummarizationSetBy = Automatic

	column 'Data da Avaliação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5d075375-4af7-49fc-9d8c-ac548d89d052
		summarizeBy: none
		sourceColumn: Data da Avaliação

		variation Variation
			isDefault
			relationship: f9a48799-2390-47ff-8019-d2e2a14315df
			defaultHierarchy: LocalDateTable_ad9c89ae-7103-4b95-801f-ffcf4d69ba7c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tempo de Avaliação'
		dataType: dateTime
		formatString: Long Time
		lineageTag: aec270b4-a9b1-43e8-8072-fb78e377638a
		summarizeBy: none
		sourceColumn: Tempo de Avaliação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Data do contato'
		dataType: dateTime
		formatString: General Date
		lineageTag: 32f24cdc-c3f8-473b-aba5-ab5e833bb8ae
		summarizeBy: none
		sourceColumn: Data do contato

		variation Variation
			isDefault
			relationship: f4a7dfd0-b536-422f-b63a-f7c1c51c8f50
			defaultHierarchy: LocalDateTable_70813571-95f1-46e7-b3fd-6c5872662838.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Duração
		dataType: string
		lineageTag: 4586bbdf-cb72-4807-a921-49e5046820fc
		summarizeBy: none
		sourceColumn: Duração

		annotation SummarizationSetBy = Automatic

	column Protocolo
		dataType: string
		lineageTag: a22bf377-e125-464b-b9f3-74806e321bd4
		summarizeBy: none
		sourceColumn: Protocolo

		annotation SummarizationSetBy = Automatic

	column Monitor
		dataType: string
		lineageTag: c8aa2ab0-f164-4f0d-91fa-e03f773850bc
		summarizeBy: none
		sourceColumn: Monitor

		annotation SummarizationSetBy = Automatic

	column Improdutivo
		dataType: string
		lineageTag: 7f8e4629-6665-4de3-8d49-fb79bd9198c0
		summarizeBy: none
		sourceColumn: Improdutivo

		annotation SummarizationSetBy = Automatic

	column TAG
		dataType: string
		lineageTag: 4c6c1f41-f1a0-41ac-8611-7ef9066a2cd5
		summarizeBy: none
		sourceColumn: TAG

		annotation SummarizationSetBy = Automatic

	column 'Nota Inicial'
		dataType: double
		lineageTag: 0d264787-44ba-4c30-b9a8-874d16412c71
		summarizeBy: sum
		sourceColumn: Nota Inicial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nota Final'
		dataType: double
		lineageTag: f443503b-c35f-4188-a5dd-07b630852616
		summarizeBy: sum
		sourceColumn: Nota Final

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tipo da avaliação:'
		dataType: string
		lineageTag: 02fa50bd-688b-4144-a15e-5f54b740692e
		summarizeBy: none
		sourceColumn: Tipo da avaliação:

		annotation SummarizationSetBy = Automatic

	column Feedback
		dataType: string
		lineageTag: aa02e47a-d5b7-43ce-aeb7-7307ae96f334
		summarizeBy: none
		sourceColumn: Feedback

		annotation SummarizationSetBy = Automatic

	column 'Data do feedback'
		dataType: dateTime
		formatString: General Date
		lineageTag: e0f41d0a-4ce3-4c71-b1e3-a74a815aaba7
		summarizeBy: none
		sourceColumn: Data do feedback

		variation Variation
			isDefault
			relationship: 6c494c5f-cbf7-4a51-94f9-e7da37e4223f
			defaultHierarchy: LocalDateTable_4f92ae3d-78f3-43ea-8862-7f5ab59c7672.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Quem aplicou feedback'
		dataType: string
		lineageTag: 25bbd7dc-1641-414b-84ff-23e372bc81da
		summarizeBy: none
		sourceColumn: Quem aplicou feedback

		annotation SummarizationSetBy = Automatic

	column 'Data da Contestação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 69b982ae-afa1-4274-88fe-9f5278322e75
		summarizeBy: none
		sourceColumn: Data da Contestação

		variation Variation
			isDefault
			relationship: 54363458-01b7-4b61-957f-4bf07394e087
			defaultHierarchy: LocalDateTable_e0f5e444-7342-410b-8f5e-7920cf354e0b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Quem contestou'
		dataType: string
		lineageTag: e960b852-636f-4690-b40c-a026fc6f7811
		summarizeBy: none
		sourceColumn: Quem contestou

		annotation SummarizationSetBy = Automatic

	column Comentário
		dataType: string
		lineageTag: 64e9e3fa-78ad-45ed-bbd7-48988a5a8c69
		summarizeBy: none
		sourceColumn: Comentário

		annotation SummarizationSetBy = Automatic

	column 'Resumo do contato'
		dataType: string
		lineageTag: 96b547ad-c385-4735-ae54-03be2b545586
		summarizeBy: none
		sourceColumn: Resumo do contato

		annotation SummarizationSetBy = Automatic

	column Empresa:
		dataType: string
		lineageTag: 1f0f1c9f-2f65-400c-8065-83251cc70816
		summarizeBy: none
		sourceColumn: Empresa:

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: c5732750-59af-477b-bfcf-ebd345aa0412
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Avaliador
		dataType: string
		lineageTag: 0b4f86da-a0bd-4faa-9d54-80585cf90f88
		summarizeBy: none
		sourceColumn: Avaliador

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 9ccdef0e-85a1-4a0a-abe7-9ec6e04519fe
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column Tempo
		dataType: double
		lineageTag: 6419085a-0724-41c3-ac7b-3ae56da24e4c
		summarizeBy: sum
		sourceColumn: Tempo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tempo Limite'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9bb044bb-129f-4c57-9d33-d3c03a1df857
		summarizeBy: none
		sourceColumn: Tempo Limite

		variation Variation
			isDefault
			relationship: cf36c291-bf56-4288-b63f-7b45b6d830d4
			defaultHierarchy: LocalDateTable_ad7d60a4-b94c-4cb9-b815-48201463bf66.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Status Feedback'
		dataType: string
		lineageTag: 5a051f59-10fe-4f4b-ad83-5766bd3aa895
		summarizeBy: none
		sourceColumn: Status Feedback

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Nota'
		dataType: string
		lineageTag: 18c8b739-8531-4df4-a30a-0f4f91fc2882
		summarizeBy: none
		sourceColumn: Tipo de Nota

		annotation SummarizationSetBy = Automatic

	column 'Status Nota'
		dataType: string
		lineageTag: 834cc13a-d41c-4432-8dca-feae731bc607
		summarizeBy: none
		sourceColumn: Status Nota

		annotation SummarizationSetBy = Automatic

	column Data = FORMAT(FT_QUALIDADE_LLM[Data da Avaliação], "DD/MM/YYYY")
		lineageTag: ca025f26-b6b1-4692-9921-e17cc5b83a66
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Senioridade = IF((TODAY()-RELATED(DIM_DATAS[dtInício]))>30,"Veterano","Novato")
		lineageTag: 6ebc0c5c-bda2-4f33-8b05-bc5c368e4a60
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tempo na Compagas (d)' = TODAY()-RELATED(DIM_DATAS[dtInício])
		dataType: int64
		formatString: 0
		lineageTag: a05bc17c-19dd-49bf-8ddc-6f8262a7f484
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	partition FT_QUALIDADE_LLM = m
		mode: import
		queryGroup: QUALIDADE
		source = ```
				let
				    Fonte = PowerPlatform.Dataflows([]),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"cd285858-e86a-4854-ae7f-7fbf647a6920" = Workspaces{[workspaceId="cd285858-e86a-4854-ae7f-7fbf647a6920"]}[Data],
				    #"aabc750c-e78b-4117-991d-304193bcebde" = #"cd285858-e86a-4854-ae7f-7fbf647a6920"{[dataflowId="aabc750c-e78b-4117-991d-304193bcebde"]}[Data],
				    #"Ft_Qualidade LLM_" = #"aabc750c-e78b-4117-991d-304193bcebde"{[entity="Ft_Qualidade LLM",version=""]}[Data],
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Ft_Qualidade LLM_",{"Arquivo de Origem", "Perfil Avaliador", "Nome da Operação"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"Data do Feedback", "Data do feedback"}, {"Quem Contestou", "Quem contestou"}, {"Comentários", "Comentário"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Tipo de Formulário", type text}, {"Nome do Formulário", type text}, {"Status", type text}, {"Agente", type text}, {"Supervisor", type text}, {"Data da Avaliação", type datetime}, {"Tempo de Avaliação", type time}, {"Data do contato", type datetime}, {"Monitor", type text}, {"Improdutivo", type text}, {"TAG", type text}, {"Nota Inicial", type number}, {"Nota Final", type number}, {"Feedback", type text}, {"Data do feedback", type datetime}, {"Quem aplicou feedback", type text}, {"Data da Contestação", type datetime}, {"Quem contestou", type text}, {"Comentário", type any}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each ([Tipo de Formulário] = "Qualidade")),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each ([Status] <> "Aguardando Análise pelo Avaliador" and [Status] <> "Aguardando Análise pelo Monitor")),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Linhas Filtradas","Qualidade","Monitoria",Replacer.ReplaceText,{"Tipo de Formulário"}),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Valor Substituído1", each Text.Contains([Nome do Formulário], "COMGÁS") or Text.Contains([Nome do Formulário], "Comgás")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas2",{"Status", "Editada por"}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Colunas Removidas",{{"Monitor", Text.Upper, type text}, {"Agente", Text.Upper, type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Texto em Maiúscula",{{"Tipo de Formulário", "Tipo da avaliação:"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas",{"Nome do Formulário",
				"Agente",
				"Supervisor",
				"Data da Avaliação",
				"Tempo de Avaliação",
				"Data do contato",
				"Duração",
				"Monitor",
				"Improdutivo",
				"TAG",
				"Nota Inicial",
				"Nota Final",
				"Tipo da avaliação:",
				"Feedback",
				"Data do feedback",
				"Quem aplicou feedback",
				"Data da Contestação",
				"Quem contestou"
				}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Reordenadas", "Resumo do contato", each ""),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Empresa:", each "Necxt"),
				    #"Nota Final / 100" = Table.TransformColumns(#"Personalização Adicionada1", {{"Nota Final", each _ / 100, type number}}),
				    #"Nota Inicial / 100" = Table.TransformColumns(#"Nota Final / 100", {{"Nota Inicial", each _ / 100, type number}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Nota Inicial / 100", "Agente", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Agente", "Funcional"}),
				    #"Coluna Tipo de Nota" = Table.AddColumn(#"Dividir Coluna por Delimitador", "Tipo", each if [Nota Final] = 100 then "Nota Máxima" else if [Nota Final] >= 1 then "NC" else "NCG"),
				    #"Texto Aparado" = Table.TransformColumns(#"Coluna Tipo de Nota",{{"Agente", Text.Trim, type text}, {"Funcional", Text.Trim, type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Texto Aparado", {{"Agente", each Text.BeforeDelimiter(_, " - "), type text}}),
				    #"Cira coluna Avaliador" = Table.AddColumn(#"Texto Extraído Antes do Delimitador", "Avaliador", each if Text.Contains([Monitor], "MONITOR AUDITOR") then "Auditor" else if Text.Contains([Monitor], "MONITOR") then "Monitor" else "Supervisor"),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Cira coluna Avaliador", "Nome do Dia", each Date.DayOfWeekName([Data da Avaliação]), type text),
				    #"Personalização Adicionada0" = Table.AddColumn(#"Nome do Dia Inserido", "Tempo", each if [Nome do Dia]="quinta-feira" and [Tipo]="NCG" 
				then 1
				else if [Nome do Dia]="quinta-feira" and [Tipo]="NC" or [Nome do Dia]="quinta-feira" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="quarta-feira" and [Tipo]="NCG" 
				then 1
				else if [Nome do Dia]="quarta-feira" and [Tipo]="NC" or [Nome do Dia]="quarta-feira" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="sexta-feira" and [Tipo]="NCG" 
				then 3
				else if [Nome do Dia]="sexta-feira" and [Tipo]="NC" or [Nome do Dia]="sexta-feira" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="sábado" and [Tipo]="NCG" 
				then 3
				else if [Nome do Dia]="sábado" and [Tipo]="NC" or [Nome do Dia]="sábado" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="domingo" and [Tipo]="NCG" 
				then 2
				else if [Nome do Dia]="domingo" and [Tipo]="NC" or [Nome do Dia]="domingo" and [Tipo]="Nota Máxima" 
				then 4
				
				else if [Tipo]="NCG" 
				then 1
				else if [Tipo]="NC" or [Tipo]="Nota Máxima" 
				then 3
				else "-"),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada0",{{"Tempo", type duration}, {"Data do feedback", type datetime}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado3", {{"Data do feedback", null}}),
				    #"Cria Coluna Tempo Limite Feed." = Table.AddColumn(#"Erros Substituídos", "Tempo Limite", each [Data da Avaliação]+[Tempo]),
				    #"Cria Coluna Status Feedback" = Table.AddColumn(#"Cria Coluna Tempo Limite Feed.", "Status Feedback", each if [Feedback] = "autofeedback" and [Data do feedback] = null and [Nota Final] = 100 then "Aplicado - Auto Feedback"
				else if [Data do feedback] = null and [Nota Final] = 100 and DateTime.LocalNow() > [Tempo Limite] then "Não Aplicado - Auto Feedback"
				else if [Data do feedback] <> null and [Data do feedback] <= [Tempo Limite] then "Aplicado - Dentro Do Prazo"
				else if [Data do feedback] <> null and [Data do feedback] > [Tempo Limite] then "Aplicado - Fora Do Prazo"
				else if [Data do feedback] = null and DateTime.LocalNow() <= [Tempo Limite] then "Não Aplicado - Dentro do Prazo"
				else if [Data do feedback] = null and DateTime.LocalNow() > [Tempo Limite] then "Não Aplicado"
				else null),
				    #"Cria Coluna Tipo Nota" = Table.AddColumn(#"Cria Coluna Status Feedback", "Tipo de Nota", each if [Nota Final] = 100 then "Nota Maxima" else if [Nota Final] = 0 then "Gravissimo" else "Alerta"),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Cria Coluna Tipo Nota", "Status Nota", each if [Nota Final] = 0 then "NCG" else if [Nota Final] = 100 then "Nota Máxima" else "NC"),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Status Feedback", type text}, {"Tipo de Nota", type text}, {"Status Nota", type text}, {"Tempo Limite", type datetime}, {"Avaliador", type text}, {"Tipo", type text}, {"Empresa:", type text}, {"Resumo do contato", type text}, {"Comentário", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado5", {"TAG"}),
				    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Duplicatas Removidas", {{"Status Feedback", ""}}),
				    #"Erros Substituídos2" = Table.ReplaceErrorValues(#"Erros Substituídos1", {{"Tempo Limite", #datetime(1899, 12, 30, 0, 0, 0)}}),
				    #"Erros Substituídos3" = Table.ReplaceErrorValues(#"Erros Substituídos2", {{"Tempo", #duration(0, 0, 0, 0)}}),
				    #"Erros Substituídos4" = Table.ReplaceErrorValues(#"Erros Substituídos3", {{"Tipo", ""}})
				in
				    #"Erros Substituídos4"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

