table GENESYS_FT_PAUSAS
	lineageTag: 5181ad1a-ad3a-49da-8a0a-92c2116f33c3

	column row_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29f01b3f-9e4f-4186-b903-411aee4b954d
		summarizeBy: none
		sourceColumn: row_date

		variation Variation
			isDefault
			relationship: 96a6df76-0f40-4f11-bd07-44dbc863fb22
			defaultHierarchy: LocalDateTable_f9491ba3-fb38-4e58-8f05-94c9f94fb1ec.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column starttime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 313f618e-6d6a-4fda-a14e-965b621a4ab1
		summarizeBy: none
		sourceColumn: starttime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column DIVISION_NAME
		dataType: string
		lineageTag: 215d3a13-2afb-4aac-902f-bc0cb1cbf9ba
		summarizeBy: none
		sourceColumn: DIVISION_NAME

		annotation SummarizationSetBy = Automatic

	column ROUTING_SKILL_NAME
		dataType: string
		lineageTag: 3bd6fafa-c1d3-4a2f-b36e-d6285edfcd30
		summarizeBy: none
		sourceColumn: ROUTING_SKILL_NAME

		annotation SummarizationSetBy = Automatic

	column Tempo_total
		dataType: double
		lineageTag: 5843263e-dfb7-4981-924b-8b2cb5611ba0
		summarizeBy: sum
		sourceColumn: Tempo_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Disponivel
		dataType: double
		lineageTag: 18ac28b8-293a-4e5b-bdf1-5014de4ef77c
		summarizeBy: sum
		sourceColumn: Disponivel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ocupado
		dataType: double
		lineageTag: ed0a8c3f-d3cb-4ee2-bd60-1f9ea423924f
		summarizeBy: sum
		sourceColumn: Ocupado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Treinamento
		dataType: double
		lineageTag: 26b83694-11c3-45b8-a78f-4fd9e143aa34
		summarizeBy: sum
		sourceColumn: Treinamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ausente
		dataType: double
		lineageTag: 2e87aedf-4aac-4710-9c11-113f92960dcd
		summarizeBy: sum
		sourceColumn: Ausente

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fora da fila'
		dataType: double
		lineageTag: 15698385-4066-48ea-af11-6672de011a5b
		summarizeBy: sum
		sourceColumn: Fora da fila

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Em fila'
		dataType: double
		lineageTag: 943cdd4e-e8a4-4b37-91f4-5f9a6318a59b
		summarizeBy: sum
		sourceColumn: Em fila

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Interagindo
		dataType: double
		lineageTag: 7fa6755b-1a0e-49dd-a5aa-4f665f1401ef
		summarizeBy: sum
		sourceColumn: Interagindo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Parado(a)
		dataType: double
		lineageTag: 735542e0-3c00-4393-96a3-6f9244389a1a
		summarizeBy: sum
		sourceColumn: Parado(a)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Online
		dataType: double
		lineageTag: 3d29ef3f-f4f0-4920-864c-fd3cd773beea
		summarizeBy: sum
		sourceColumn: Online

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column N_Respondendo
		dataType: double
		lineageTag: 069d7785-c253-4b61-834d-846608e94bce
		summarizeBy: sum
		sourceColumn: N_Respondendo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pausa
		dataType: double
		lineageTag: a026efa8-cab7-4000-ac74-9a9f2c674b53
		summarizeBy: sum
		sourceColumn: Pausa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lanche
		dataType: double
		lineageTag: 22fd5d58-5ced-44f8-a734-d893c788f07e
		summarizeBy: sum
		sourceColumn: Lanche

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DATA HORA'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6cba0c3c-339d-460d-b4b3-b9d335dcc14c
		summarizeBy: none
		sourceColumn: DATA HORA

		variation Variation
			isDefault
			relationship: fd52a961-d36c-41f2-85f3-5c059d821b53
			defaultHierarchy: LocalDateTable_8aa7de82-37ec-42ca-a1ed-607d766cc490.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'TL - PNR' =
			
			
			var TempoLogado = GENESYS_FT_PAUSAS[Tempo_total]
			var PausaNR = GENESYS_FT_PAUSAS[Lanche] + GENESYS_FT_PAUSAS[Pausa]
			
			
			RETURN
			
			TempoLogado - PausaNR
		lineageTag: e0d3ea5d-0198-4499-b042-e64671e74a18
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reuniao
		dataType: double
		lineageTag: f5049e1f-6664-48a8-93a8-201fe7c3f88a
		summarizeBy: sum
		sourceColumn: Reuniao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CONTA PA' = GENESYS_FT_PAUSAS[Tempo_total]/1800
		formatString: 0.00
		lineageTag: c42cdc5c-5fb2-49cf-ac31-699e8d514ff6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MD
		dataType: string
		lineageTag: 644cb092-f9ea-43f8-8895-a57f69d1513c
		summarizeBy: none
		sourceColumn: MD

		annotation SummarizationSetBy = Automatic

	column CHAVE_INTERVALO = FORMAT(GENESYS_FT_PAUSAS[DATA HORA], "DD/MM/YYYY HH:MM:SS")
		lineageTag: 07a1ca42-6898-4dc8-8fb5-da87672a8435
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'HC BRUTO'
		dataType: double
		lineageTag: f3d6fc99-7446-4bcb-92e1-f32ae9f6776f
		summarizeBy: sum
		sourceColumn: HC BRUTO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'HC LIQUIDO'
		dataType: double
		lineageTag: 7bd8ceae-b067-4a84-a288-781b2a6b7e68
		summarizeBy: sum
		sourceColumn: HC LIQUIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'HC BRUTO Acumulado'
		dataType: double
		lineageTag: 83451961-ce10-403a-bf09-d53f8c23fe74
		summarizeBy: sum
		sourceColumn: HC BRUTO Acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'HC LIQUIDO Acumulado'
		dataType: double
		lineageTag: 9cb48971-4a2d-44aa-b55b-f74c37e94797
		summarizeBy: sum
		sourceColumn: HC LIQUIDO Acumulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition GENESYS_FT_PAUSAS = m
		mode: import
		queryGroup: FT_GENESYS
		source = ```
				let
				    Fonte = PowerBI.Dataflows(null),
				    #"9099524d-5d03-49b4-b51f-776c29c149aa" = Fonte{[workspaceId="9099524d-5d03-49b4-b51f-776c29c149aa"]}[Data],
				    #"ba87d457-6b14-43c8-97dd-2822cda24661" = #"9099524d-5d03-49b4-b51f-776c29c149aa"{[dataflowId="ba87d457-6b14-43c8-97dd-2822cda24661"]}[Data],
				    COMGAS_FT_PAUSAS = #"ba87d457-6b14-43c8-97dd-2822cda24661"{[entity="COMGAS_FT_PAUSAS"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(COMGAS_FT_PAUSAS, each [DATA HORA] >= #"DATA INICIO GENESYS"),
				    
				    // Definir os routing skills que serão consolidados
				    RoutingSkillsConsolidados = {"ContaPAAtendimento08000", "ContaPAContas", "ContaPAEmergencialAcompanhamentoObras"},
				    
				    // Filtrar apenas os routing skills que pertencem ao consolidado
				    SkillsConsolidados = Table.SelectRows(#"Linhas Filtradas", each List.Contains(RoutingSkillsConsolidados, [ROUTING_SKILL_NAME])),
				    
				    // Agrupar por data/hora e somar todas as colunas numéricas
				    Consolidado = Table.Group(SkillsConsolidados, 
				        {"row_date", "starttime", "DIVISION_NAME", "DATA HORA"}, 
				        {
				            {"ROUTING_SKILL_NAME", each "CONSOLIDADO", type text},
				            {"Tempo_total", each List.Sum([Tempo_total]), type number},
				            {"Disponivel", each List.Sum([Disponivel]), type number},
				            {"Ocupado", each List.Sum([Ocupado]), type number},
				            {"Treinamento", each List.Sum([Treinamento]), type number},
				            {"Ausente", each List.Sum([Ausente]), type number},
				            {"Fora da fila", each List.Sum([#"Fora da fila"]), type number},
				            {"Em fila", each List.Sum([#"Em fila"]), type number},
				            {"Interagindo", each List.Sum([Interagindo]), type number},
				            {"Parado(a)", each List.Sum([#"Parado(a)"]), type number},
				            {"Online", each List.Sum([Online]), type number},
				            {"N_Respondendo", each List.Sum([N_Respondendo]), type number},
				            {"Pausa", each List.Sum([Pausa]), type number},
				            {"Lanche", each List.Sum([Lanche]), type number},
				            {"Reuniao", each List.Sum([Reuniao]), type number}
				        }
				    ),
				    
				    // Combinar a tabela original com as linhas consolidadas
				    TabelaFinal = Table.Combine({#"Linhas Filtradas", Consolidado}),
				    
				    // Ordenar por routing skill, DATA HORA (CRUCIAL para o acumulado)
				    Ordenado = Table.Sort(TabelaFinal,{
				        {"ROUTING_SKILL_NAME", Order.Ascending},
				        {"DATA HORA", Order.Ascending}
				    }),
				    
				    // Adicionar coluna HC BRUTO
				    #"Personalização Adicionada" = Table.AddColumn(Ordenado, "HC BRUTO", each [Tempo_total]/22800, type number),
				    
				    // Adicionar coluna HC LIQUIDO
				    #"Personalização Adicionada2" = Table.AddColumn(#"Personalização Adicionada", "HC LIQUIDO", each ([Tempo_total] - [Lanche] - [Pausa]) / 22800, type number),
				    
				    // *** CORREÇÃO: AGORA AGRUPAMOS POR SKILL E DATA (apenas data) ***
				    // Extrair apenas a data da DATA HORA
				    #"Data Adicionada" = Table.AddColumn(#"Personalização Adicionada2", "Data", each DateTime.Date([DATA HORA]), type date),
				    
				    // Agrupar por ROUTING_SKILL_NAME e Data para calcular acumulado
				    #"Agrupado por Skill e Data" = Table.Group(#"Data Adicionada", 
				        {"ROUTING_SKILL_NAME", "Data"}, 
				        {
				            {"DadosAgrupados", each 
				                let
				                    // Ordenar por DATA HORA dentro de cada skill/data
				                    OrdenadoPorDataHora = Table.Sort(_, {"DATA HORA", Order.Ascending}),
				                    // Calcular acumulado para HC BRUTO e HC LIQUIDO
				                    HCBrutoList = Table.ToRows(Table.SelectColumns(OrdenadoPorDataHora, {"HC BRUTO"})),
				                    HCLiquidoList = Table.ToRows(Table.SelectColumns(OrdenadoPorDataHora, {"HC LIQUIDO"})),
				                    
				                    AcumuladoBruto = List.Accumulate(
				                        HCBrutoList,
				                        {},
				                        (state, current) => 
				                            let 
				                                valorAtual = List.Sum(current),
				                                acumuladoAnterior = if List.IsEmpty(state) then 0 else List.Last(state),
				                                novoAcumulado = acumuladoAnterior + valorAtual
				                            in
				                                state & {novoAcumulado}
				                    ),
				                    
				                    AcumuladoLiquido = List.Accumulate(
				                        HCLiquidoList,
				                        {},
				                        (state, current) => 
				                            let 
				                                valorAtual = List.Sum(current),
				                                acumuladoAnterior = if List.IsEmpty(state) then 0 else List.Last(state),
				                                novoAcumulado = acumuladoAnterior + valorAtual
				                            in
				                                state & {novoAcumulado}
				                    ),
				                    
				                    // Adicionar colunas com valores acumulados
				                    TabelaComAcumulado = Table.FromColumns(
				                        Table.ToColumns(OrdenadoPorDataHora) & {AcumuladoBruto} & {AcumuladoLiquido},
				                        Table.ColumnNames(OrdenadoPorDataHora) & {"HC BRUTO Acumulado"} & {"HC LIQUIDO Acumulado"}
				                    )
				                in
				                    TabelaComAcumulado
				            , type table}
				        }
				    ),
				    
				    // Expandir a tabela novamente
				    #"Expandido" = Table.ExpandTableColumn(#"Agrupado por Skill e Data", "DadosAgrupados", 
				        List.RemoveItems(Table.ColumnNames(#"Data Adicionada"), {"ROUTING_SKILL_NAME", "Data"}) & {"HC BRUTO Acumulado"} & {"HC LIQUIDO Acumulado"}),
				    
				    // Remover coluna Data auxiliar se não for necessária
				    #"Data Removida" = Table.RemoveColumns(#"Expandido",{"Data"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Data Removida",{
				        {"row_date", type date}, 
				        {"Tempo_total", type number}, 
				        {"Disponivel", type number}, 
				        {"Ocupado", type number}, 
				        {"Treinamento", type number}, 
				        {"Ausente", type number}, 
				        {"Fora da fila", type number}, 
				        {"Em fila", type number}, 
				        {"Interagindo", type number}, 
				        {"Parado(a)", type number}, 
				        {"Online", type number}, 
				        {"N_Respondendo", type number}, 
				        {"Pausa", type number}, 
				        {"Lanche", type number}, 
				        {"Reuniao", type number}, 
				        {"HC BRUTO", type number}, 
				        {"HC LIQUIDO", type number},
				        {"HC BRUTO Acumulado", type number},
				        {"HC LIQUIDO Acumulado", type number},
				        {"MD", type text}, 
				        {"DIVISION_NAME", type text}, 
				        {"starttime", type time}, 
				        {"DATA HORA", type datetime}
				    })
				
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

