table Tabela_Medidas_Panorama
	lineageTag: d1a5290c-d060-4e74-a53f-0bae5f5a141a

	measure Valor_Medida_Formatada = ```
			
			VAR Valor = [Valor_Medida_Panorama]
			VAR MedidaSelecionada = SELECTEDVALUE('Tabela_Medidas_Panorama'[Medida])
			
			RETURN
			SWITCH(
			    TRUE(),
			    // Percentuais (formatar com duas casas decimais e símbolo %)
			    MedidaSelecionada IN {
			        "NS Projetado", 
			        "NS Realizado", 
			        "NS % Desvio", 
			        "Volume % Desvio", 
			        "% Desvio Atendido Projetado", 
			        "% Atendido", 
			        "% Abandono", 
			        "TMO % Desvio"
			    }, FORMAT(Valor, "0.00%"),
			
			    // Valores com uma casa decimal (ex: TMA Realizado)
			    MedidaSelecionada = "TMA Realizado", FORMAT(Valor, "0"),
			
			    MedidaSelecionada IN { "Evolução NS Realizado", "Evolução TMO" }, FORMAT(Valor, "0.00%"),
			
			
			    // Demais valores (números inteiros)
			    TRUE(), FORMAT(Valor, "0")
			)
			
			```
		lineageTag: c3211f02-2f29-4e1d-8c1e-01715205590b

	measure Valor_Medida_Panorama = ```
			
			VAR Hoje = TODAY()
			VAR PrimeiroDia3MesesAtras = EOMONTH(Hoje, -3) + 1
			VAR UltimoDiaMesAtual = EOMONTH(Hoje, 0)
			
			VAR MedidaSelecionada = SELECTEDVALUE('Tabela_Medidas_Panorama'[Medida])
			
			VAR PeriodoFiltro =
			    FILTER(
			        ALL('!DIM_CALENDARIO'[Date]),
			        '!DIM_CALENDARIO'[Date] >= PrimeiroDia3MesesAtras &&
			        '!DIM_CALENDARIO'[Date] <= UltimoDiaMesAtual
			    )
			
			RETURN
			SWITCH(
			    TRUE(),
			    MedidaSelecionada = "NS Projetado",         
			        CALCULATE([@NS], PeriodoFiltro),
			
			    MedidaSelecionada = "NS Realizado",         
			        CALCULATE([NS Realizado], PeriodoFiltro),
			
			    MedidaSelecionada = "NS % Desvio",          
			        CALCULATE([%NS], PeriodoFiltro), 
			
			    MedidaSelecionada = "Recebido Projetado",   
			        CALCULATE([@RECEBIDAS], PeriodoFiltro),
			
			    MedidaSelecionada = "Recebido Realizado",   
			        CALCULATE([RECEBIDAS], PeriodoFiltro),
			
			    MedidaSelecionada = "Volume % Desvio",      
			        CALCULATE([%RECEBIDAS], PeriodoFiltro),
			
			    MedidaSelecionada = "Atendido Projetado",   
			        CALCULATE([@ATENDIDAS], PeriodoFiltro),
			
			    MedidaSelecionada = "Atendido Realizado",   
			        CALCULATE([ATENDIDAS], PeriodoFiltro),
			
			    MedidaSelecionada = "% Desvio Atendido Projetado", 
			        CALCULATE([%ATENDIDAS], PeriodoFiltro),
			
			    MedidaSelecionada = "% Atendido",            
			        CALCULATE([%ATENDIDO], PeriodoFiltro),
			
			    MedidaSelecionada = "Abandonadas",           
			        CALCULATE([ABANDONADAS], PeriodoFiltro),
			
			    MedidaSelecionada = "% Abandono",            
			        CALCULATE([%ABANDONADAS], PeriodoFiltro),
			
			    MedidaSelecionada = "TMO Projetado",         
			        CALCULATE([@TMO], PeriodoFiltro),
			
			    MedidaSelecionada = "TMO Realizado",         
			        CALCULATE([TMO], PeriodoFiltro),
			
			    MedidaSelecionada = "TMA Realizado",         
			        CALCULATE([TMA], PeriodoFiltro),
			
			    MedidaSelecionada = "TMO % Desvio",          
			        CALCULATE([%TMO], PeriodoFiltro),
			    MedidaSelecionada = "Evolução NS Realizado",         
			        CALCULATE([Evolução NS Realizado], PeriodoFiltro),
			        MedidaSelecionada = "Evolução TMO",         
			        CALCULATE([Evolução TMO], PeriodoFiltro),
			    BLANK()
			)
			
			```
		lineageTag: adf40928-126e-4f84-a25c-eb74b2114663

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ordem
		formatString: 0
		lineageTag: 6183810f-7eec-4d53-9e3d-4c2a0e4f2675
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Ordem]

		annotation SummarizationSetBy = Automatic

	column Medida
		lineageTag: 424315e1-8f70-455c-a4b2-7fc492ff5702
		summarizeBy: none
		isNameInferred
		sourceColumn: [Medida]

		annotation SummarizationSetBy = Automatic

	partition Tabela_Medidas_Panorama = calculated
		mode: import
		source = ```
				
				DATATABLE(
				    "Ordem", INTEGER,
				    "Medida", STRING,
				    {
				        { 1, "NS Projetado" },
				        { 2, "NS Realizado" },
				        { 3, "NS % Desvio" },
				        { 4, "Evolução NS Realizado" },
				        { 5, "Recebido Projetado" },
				        { 6, "Recebido Realizado" },
				        { 7, "Volume % Desvio" },
				        { 8, "Atendido Projetado" },
				        { 9, "Atendido Realizado" },
				        { 10, "% Desvio Atendido Projetado" },
				        { 11, "% Atendido" },
				        { 12, "Abandonadas" },
				        { 13, "% Abandono" },
				        { 14, "TMO Projetado" },
				        { 15, "TMO Realizado" },
				        { 16, "TMA Realizado" },
				        { 17, "TMO % Desvio" },
				        { 18, "Evolução TMO" }
				    }
				)
				
				```

	annotation PBI_Id = cdc678bc6659440e9fee317ca26a64db

