table !DIM_SKILL
	lineageTag: 3dbc296e-5f37-43e4-b10f-5c4bc09b01a2

	column SKILL
		dataType: string
		lineageTag: 0d9cd0ad-3b85-4e72-9afe-2d0fe88509c2
		summarizeBy: none
		sourceColumn: SKILL

		annotation SummarizationSetBy = Automatic

	column FILA
		dataType: string
		lineageTag: 2e286781-70ed-4666-8344-d8ddfe4214c4
		summarizeBy: none
		sourceColumn: FILA

		annotation SummarizationSetBy = Automatic

	column FORECAST
		dataType: string
		lineageTag: 49ad423a-eb0c-4eb3-b389-5e009a02cf2d
		summarizeBy: none
		sourceColumn: FORECAST

		annotation SummarizationSetBy = Automatic

	column CONTA_PA
		dataType: string
		lineageTag: 5a45b5aa-1f45-48f1-b893-828ff5ecd9a0
		summarizeBy: none
		sourceColumn: CONTA_PA

		annotation SummarizationSetBy = Automatic

	column FILTRO
		dataType: string
		lineageTag: b42eec18-9b45-4b94-97de-30d84747d3a9
		summarizeBy: none
		sourceColumn: FILTRO
		sortByColumn: INDICE

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column INDICE
		dataType: string
		lineageTag: 66fcc90e-a8be-4e72-90e0-4fa5708ec754
		summarizeBy: none
		sourceColumn: INDICE

		annotation SummarizationSetBy = Automatic

	column TEMPO
		dataType: double
		lineageTag: 52015a48-33ce-4417-a987-8c19d0c93e2f
		summarizeBy: sum
		sourceColumn: TEMPO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition !DIM_SKILL = m
		mode: import
		queryGroup: DIMENSÕES
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVhLbtswEL1K4FWLZmHZTZouVUstBCSWITvZJIFBy4xLgBYDSgqKHqG36Kon6Al8sVA/k5JIWbIZJXAA8s3wzZAczpC6vx+4cURJODgfTNzp3L12LNNyWe+D0P14UGqw/9HoajgcPJ7fDzzo/wRbsAZ6aS24QtFbuXrrmVqJ5xGI4tD0yfYZBMwEDCKi1cA1RFFMwQ1cozWhWqkXlPhgwegxoGgN1lAru4kjSIEPyB0MfKR/YTz4DHRHdL7KMJwBCjDEmunNCAbrbCnsLaSbZGEA1mpiAgIf4reIQ7RJNtODOGu81cJMCJtAGCISsKAEWq10G9uCeXx5MT4fJ3/K8/QdYSDMbsh8GTLYXNhTy7mxpwv3rMDYzCMwM1tqjyQOlBLy+1jO8muvtmsZslfr+7ra75zrp7Hn/S6Sb69mK9mtV9vS2tCrB4q7Rq8+KEtY4oWAlL10VzTNSfaN7f2wpxPH5M50GHT2yf3mmXOGjVuXj3f1S3oFSjxKbeSXi0U6MrdaF3yW7AK/ImsgO21LlaOLFdr9ydf1Qu+eNRGwX7EjZatu/JIcYgRmlETEJ5jcAcyQ3Ohe/EAfgoTk9s6xXE8Mi0Kl0gUV7UtpqaganwJiY7hBLxCfvZ8LTvBEKCve/axC6ZKi7lT7RhK6+TULBOFTmqTsXz6MiGVZTNYNVkukhpJ6mxXb8sBWeIOoakx5mk4TH9aoOgJpKpoRmuas9qAK5wY8ttQ0IOymWBSaNogU5KQNB/s4UbOUG25KQ8fKDoibZl3JKKcrtNE54JCYX05XaKMjbI+0BHdBlQJuhJdjWavU4YOk98n2oAqvZRRp8TxWdkAsHvLSg7C5W0fEiMrfV/WG2OYD0tywv/kIibcRU8CctvphpbFbRzhR7bl6GJBh4j7XPzu0xRSwuI/FQ0/WKnWEKdZfp+0gOcqJFS+gbrBaIs3q5TrZXdAkkxsMn2EiR7+zZNYgcpiApcI4+4iY3cWWgv6yA9eXfaQT5qOP0rBWNDNDcumVwLMB4Zzg2CcwzJTKgNT9TGuZqO3+7f7LR34tjJQo1J2CXK1hDAXKOIwoKnR4R7IGamXD4Jme+myNnS1ZIYzYKSNp8m4LFqZy4TKX7v42jDFG/ACzLc/OkbxZ0MulxrhFhJ76IbUWdpr4KuGng7UcVZoYhQjTwSiPIh3MYticzPf4Cg==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SKILL = _t, FILA = _t, FORECAST = _t, CONTA_PA = _t, FILTRO = _t, INDICE = _t, TEMPO = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"SKILL", type text}, {"FILA", type text}, {"CONTA_PA", type text}, {"TEMPO", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

