table !Medidas
	lineageTag: 48ad387a-7da0-4a39-962d-45a26ab2282a

	measure Atualização =
			//"Atualizado em: " & SELECTEDVALUE('Dim_Atualização'[Data e Hora Certa]) & ", com dados até: " & MAX(SUA TABELA)
			
			"Atualizado em: " & SELECTEDVALUE('!DIM_ATUALIZAÇÃO'[Data e Hora Certa]) & ", com dados até: " & CALCULATE(MAX('@FT_FORECAST'[Data]), '!DIM_CALENDARIO'[Intervalo_Status] = 1, REMOVEFILTERS())
		displayFolder: Atualização
		lineageTag: 1795c91e-a257-412b-a497-bd8ed9337c7c

	measure ATENDIDAS =
			
			
			VAR GENESYS = SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS])
			
			
			RETURN
			
			GENESYS
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 4bc9fc38-539f-4a3e-a9ab-43b6c7f879bf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TRANSFERIDAS = SUM(GENESYS_FT_TRANSFERIDAS[TOTAL])
		formatString: 0
		displayFolder: Telefonia
		lineageTag: c12b18bf-3ae3-404d-8b0a-0db45c68e2cb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ABANDONADAS =
			
			
			VAR ABN = SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS])
			
			
			
			
			
			RETURN
			
			IF(ABN=0,BLANK(),ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 9ef906be-c0cf-45df-a221-a96d1296853f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure RECEBIDAS =
			
			
			-- JÁ CONTEMPLA GENESYS E AVAYA
			VAR RECEBIDAS =  SUM(GENESYS_FT_RECEBIDAS[RECEBIDAS])
			
			RETURN
			
			IF(RECEBIDAS = 0, BLANK(), RECEBIDAS)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: f0b1a906-c8f7-4a82-9aa3-213b25568d9d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'NS Realizado' =
			
			
			VAR ATENDIDAS_NIVEL = [Atendidas no Nível 10s]
			VAR RECEBIDAS = [RECEBIDAS]
			VAR ABN_10 = [ABANDONADAS até 10s Total]
			
			
			RETURN
			
			DIVIDE(ATENDIDAS_NIVEL,(RECEBIDAS - ABN_10), BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 66335235-1bd9-4dc2-9d5d-2f3aa285c881

	measure TMA =
			
			
			
			VAR TMA = SUM(GENESYS_FT_FINALIZADAS[TALK_COMPLETE_TIME])
			
			
			VAR ATENDIDAS = SUM(GENESYS_FT_FINALIZADAS[FINALIZADAS])
			
			RETURN
			
			DIVIDE( TMA, ATENDIDAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: ae314a0a-e484-4a4e-8d50-cb633e6f4222

		annotation PBI_FormatHint = {"isDecimal":true}

	measure PA =
			
			
			var pa_genesys = MAX(GENESYS_FT_PAUSAS[CONTA PA])
			
			
			RETURN
			
			pa_genesys
		formatString: 0
		displayFolder: Tempos
		lineageTag: 8ee1291b-b728-4cd8-bd30-95259c1bd0db

	measure 'Atendidas no Nível 10s' = ```
			
			
			VAR GENESYS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 10)
			
			
			
			RETURN
			
			GENESYS
			
			
			```
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 5151db96-c7f3-4b3b-a0e1-3408e9aa1041

	measure TMO =
			
			
			VAR TMO = SUM(GENESYS_FT_FINALIZADAS[TEMPO_OPERACIONAL])
			VAR ATENDIDAS = SUM(GENESYS_FT_FINALIZADAS[FINALIZADAS])
			RETURN
			DIVIDE( TMO, ATENDIDAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 993e2a91-d4da-4aa7-b635-ed4dd351d6c0

	measure TME =
			
			
			
			VAR TME= SUM(GENESYS_FT_ATENDIDAS[ANSWERED_TIME])
			VAR ATENDIDAS = [ATENDIDAS]
			RETURN
			DIVIDE( TME, ATENDIDAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 437022eb-9a5a-4386-8319-d29cb6587c79

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'ABANDONADAS até 20s' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 20)
			
			
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 0c27fbc3-1188-461e-a511-1ee064be06f2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %ABANDONADAS = DIVIDE([ABANDONADAS], [RECEBIDAS], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 1d89b687-1602-4c7b-bab4-ef65da8306bf

	measure Trafego =
			
			
			--[ATENDIDAS] * [TMO] + [ABANDONADAS] * [TMABN]
			
			[RECEBIDAS] * [TMO]
		formatString: 0
		displayFolder: Telefonia
		lineageTag: ada682de-8737-42bb-8365-b56ad5758132

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %ATENDIDO = DIVIDE([ATENDIDAS],[RECEBIDAS], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: d4fd3ffc-dd68-40b1-987d-4c5cbff6af95

	measure 'Tempo Logado' = ```
			
			VAR TL = CALCULATE(SUM(GENESYS_FT_PAUSAS[Tempo_total]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)")
			VAR T =   TL
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			 
			SWITCH(TRUE(),
			vresultado = 0, BLANK(),
			vresultado
			)
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: d288af86-ffcf-43dc-9255-a9b81988bc45

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Pausa Total' = ```
			
			
			VAR PAUSAS = CALCULATE(SUM(GENESYS_FT_PAUSAS[Pausa]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)") +  
			                    CALCULATE(SUM(GENESYS_FT_PAUSAS[Lanche]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)") +  
			                    CALCULATE(SUM(GENESYS_FT_PAUSAS[Treinamento]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)")
			
			VAR T = PAUSAS   
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			 
			SWITCH(TRUE(),
			vresultado = 0, BLANK(),
			vresultado
			)
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: 42732193-d7bf-408e-ad9a-991106ca8170

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Tempo Produtivo' = ```
			
			
			-- TEMPOS GENESYS
			VAR TEMPO_LOGADO = CALCULATE(SUM(GENESYS_FT_PAUSAS[Tempo_total]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)")
			VAR TEMPO_PAUSAS = CALCULATE(SUM(GENESYS_FT_PAUSAS[Pausa]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)") +  
			                     CALCULATE(SUM(GENESYS_FT_PAUSAS[Lanche]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)") +  
			                     CALCULATE(SUM(GENESYS_FT_PAUSAS[Treinamento]), '!DIM_SKILL'[SKILL] <> "(CONSOLIDADO)")
			
			--CONSOLIDADO
			
			VAR TEMPO_PRODUTIVO = TEMPO_LOGADO - TEMPO_PAUSAS
			VAR T =   TEMPO_PRODUTIVO
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			 
			SWITCH(TRUE(),
			vresultado = 0, BLANK(),
			vresultado
			)
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: 960a4197-ed21-4410-8bf0-a54b5ea7b396

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Carga HC' = 22800
		formatString: 0
		displayFolder: Tempos
		lineageTag: d4418ce3-083b-4707-891a-ed5cea432e8d

	measure 'HC Bruto' =
			
			
			VAR MAX_HC_GENESYS = MAX(GENESYS_FT_PAUSAS[HC BRUTO Acumulado])
			
			
			RETURN
			SWITCH(TRUE(),
			ISBLANK([Tempo Logado]), BLANK(),
			MAX_HC_GENESYS)
		formatString: 0
		displayFolder: Tempos
		lineageTag: 8592d18b-ecc5-4969-a4f9-bd0ab4573533

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'HC Liquido Real' =
			
			
			
			VAR MAX_HC_GENESYS = MAX(GENESYS_FT_PAUSAS[HC LIQUIDO Acumulado])
			
			
			RETURN
			SWITCH(TRUE(),
			ISBLANK([Tempo Logado]), BLANK(),
			MAX_HC_GENESYS)
		formatString: 0
		displayFolder: Tempos
		lineageTag: 4ac88930-d39c-4a7a-8cef-9f88b38aa59e

	measure TMABN =
			
			
			VAR TMABN = SUM(GENESYS_FT_ABANDONADAS[TEMPO_ABANDONO]) --SUM(GENESYS_FT_ABANDONADAS[ABANDON_TIME])
			VAR ABANDONADAS = [ABANDONADAS]
			
			RETURN
			
			DIVIDE( TMABN, ABANDONADAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: a076bf18-6314-4159-a298-789d9131027e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% POCC' =
			
			VAR TrafficInDays = [Trafego]/86400
			VAR AvailableTimeInDays = SUMX(GENESYS_FT_PAUSAS, GENESYS_FT_PAUSAS[Tempo_total] - (GENESYS_FT_PAUSAS[Pausa] + GENESYS_FT_PAUSAS[Lanche] + GENESYS_FT_PAUSAS[Treinamento]))/86400
			VAR RawPercentage = DIVIDE(TrafficInDays, AvailableTimeInDays, 0)
			RETURN
			    IF(RawPercentage > 1, 1, RawPercentage)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Tempos
		lineageTag: b5bfbe47-e6c2-4ef2-9775-f631287a36e0

	measure 'Pausa NR' = ```
			
			
			VAR NR = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche])
			VAR T =   NR
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			RETURN
			 
			vresultado
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: 22fc4bdd-0bf2-4ee3-81f6-369e0fe0abb6

		annotation PBI_FormatHint = {"isCustom":true}

	measure @RECEBIDAS =
			
			
			VAR A = SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			
			RETURN
			IF(
			    A = 0 ,
			    BLANK(),
			    A
			)
		formatString: 0
		displayFolder: Forecast
		lineageTag: 23284297-4a87-432c-855d-327f90a20c88

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @ATENDIDAS = ```
			
			
			
			VAR RECEBIDAS = [@RECEBIDAS]
			VAR FATOR = 0.9
			VAR A = RECEBIDAS * FATOR
			
			
			RETURN
			
			IF(A=0,BLANK(),A)
			
			```
		formatString: 0
		displayFolder: Forecast
		lineageTag: d3fe2680-3f33-4a60-a9c0-e142bdd44728

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @NS =
			
			
			VAR TotalPonderado = SUM('@FT_FORECAST'[Nível de Serviço POND])
			VAR VolumeProjetado = SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			RETURN
			IF(
			    ISBLANK(VolumeProjetado) || VolumeProjetado = 0,BLANK(),
			    DIVIDE(
			        TotalPonderado,
			        VolumeProjetado,
			        0
			    )/100
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: 68c0aec8-3289-48f2-ae2b-4fd56a59753a

	measure 'Atendidas Fora do Nível 10s' = ```
			
			 
			VAR GENESYS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] > 10)
			
			
			   RETURN
			    
			    GENESYS 
			              
			```
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 39730fb3-7cac-430f-8cd1-c6fcedf54d1b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @PA =
			
			SWITCH(TRUE(),
			MAX('@FT_FORECAST'[RECURSOS PREVISTOS (HC)]) = 0, BLANK(),
			MAX('@FT_FORECAST'[RECURSOS PREVISTOS (HC)])
			)
		formatString: 0
		displayFolder: Forecast
		lineageTag: 61e224c6-edbe-447f-937e-7fdc25e37dfe

	measure @TRAFEGO =
			
			
			
			
			SUMX('@FT_FORECAST','@FT_FORECAST'[Chamadas recebidas PREVISTO]*'@FT_FORECAST'[TMO PREVISTO])
		formatString: 0
		displayFolder: Forecast
		lineageTag: 302fb095-348b-4726-82c8-d3c28e592848

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @TMO = ```
			
			 
			VAR TotalTMO = SUM('@FT_FORECAST'[POND TMO PREVISTO])
			VAR TotalChamadas = SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			
			RETURN
			IF(
			    TotalChamadas = 0 || ISBLANK(TotalChamadas),
			    BLANK(),
			    DIVIDE(
			        TotalTMO,
			        TotalChamadas,
			        BLANK()
			    )
			)
			
			```
		formatString: 0
		displayFolder: Forecast
		lineageTag: 29f07a22-b4af-4b45-ba12-faa9a5601125

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '@HC Líquido Previsto' =
			
			SWITCH(TRUE(),
			ISBLANK([@HORAS CONTRATADAS]), BLANK(),
			MAX('@FT_FORECAST'[HC LÍQUIDO Acumulado]))
		formatString: 0
		displayFolder: Forecast
		lineageTag: 23c6ef74-27e0-4c93-93e2-b554d8a05537

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '@HORAS CONTRATADAS' =
			
			
			VAR T = SUM('@FT_FORECAST'[RECURSOS PREVISTOS (HC)])*1800
			VAR H = INT(T/3600)
			VAR M = INT((T - (H * 3600))/60)
			VAR S = MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			SWITCH(TRUE(),
			vresultado = 0, BLANK(),
			vresultado
			)
		formatString: 00:00:00
		displayFolder: Forecast
		lineageTag: f295159a-9086-4ffa-83b1-8c4247d30de6

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'ABANDONADAS Acima 10s' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] > 10)
			
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 8792827d-5bae-4ba3-aad9-da752ba254dc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @PAUSAS =
			
			VAR T = [@HC Líquido Previsto]*2400
			VAR H = INT(T/3600)
			VAR M = INT((T - (H * 3600))/60)
			VAR S = MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			vresultado
		formatString: 00:00:00
		displayFolder: Forecast
		lineageTag: 0a096740-6e26-434b-b76b-b5b612277d57

		annotation PBI_FormatHint = {"isCustom":true}

	measure %RECEBIDAS =
			
			VAR A = DIVIDE([RECEBIDAS],[@RECEBIDAS], BLANK()) - 1
			
			RETURN
			
			IF(ISBLANK([@RECEBIDAS]),BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: c8537b2c-8216-4967-8491-984c65c9a200

	measure %ATENDIDAS =
			
			VAR A = DIVIDE([atendidas],[@atendidas], BLANK()) - 1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@atendidas]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 86da3880-c0b4-4329-871d-da5c2c35a273

	measure %NS = ```
			
			
			   VAR A = [NS Realizado]-[@NS]
			
			   RETURN
			
			   SWITCH(TRUE(),
			    ISBLANK([NS Realizado]), BLANK(),
			    ISBLANK([@NS]), BLANK(),
			    A
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: fab3d74e-ff86-4098-8d85-50ecf58c8457

	measure %PA =
			
			
			VAR A = DIVIDE([PA],[@PA],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@PA]), BLANK(),
			    [@PA] = 0, BLANK(), A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: c800fdea-4b1d-4023-bed0-b26b3241aeb5

	measure %TRAFEGO =
			
			
			VAR A = DIVIDE([Trafego],[@TRAFEGO],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TRAFEGO]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 69b521d7-4936-47a0-aa42-fe4a052a2d99

	measure %TMO =
			
			
			VAR A = DIVIDE([TMO],[@TMO],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TMO]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: f3dfffee-af80-454f-a032-c45bc20784c4

	measure %HC =
			
			
			VAR A = DIVIDE([HC Liquido Real],[@HC Líquido Previsto],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@HC Líquido Previsto]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: f73f45ac-ac43-4041-b710-5793a05161a2

	measure '%Tempo Logado' =
			
			
			-- TEMPO LOGADO
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			
			VAR A = DIVIDE(TEMPO_LOGADO,SUM('@FT_FORECAST'[RECURSOS PREVISTOS (HC)])*1800,BLANK()) - 1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@HORAS CONTRATADAS]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: c3627589-1ed4-4318-9f96-4bb67d8ca4d6

	measure '%Tempo Produtivo' =
			
			
			-- TEMPO LOGADO
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			
			-- TEMPO EM PAUSA
			VAR TEMPO_PAUSAS = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche]) +  SUM(GENESYS_FT_PAUSAS[Treinamento])
			VAR TEMPO_PRODUTIVO = TEMPO_LOGADO - TEMPO_PAUSAS
			VAR A = DIVIDE(TEMPO_PRODUTIVO, TEMPO_LOGADO,BLANK())
			
			RETURN
			
			 SWITCH(TRUE(),   ISBLANK([Tempo Logado]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: a04a99df-acc4-497e-aa24-d283c1b78fac

	measure %PAUSA =
			
			
			-- TEMPO LOGADO
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			
			-- TEMPO EM PAUSA
			VAR TEMPO_PAUSAS = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche]) +  SUM(GENESYS_FT_PAUSAS[Treinamento])
			VAR TEMPO_PRODUTIVO = TEMPO_LOGADO - TEMPO_PAUSAS
			
			VAR A = DIVIDE(TEMPO_PAUSAS, TEMPO_LOGADO,BLANK())
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([Tempo Logado]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 12a7aa60-fa0b-4f88-abe6-58ca8053098c

	measure '%Variação Abandono' = ```
			
			
			
			var a = [%ABANDONADAS] - 0.05
			RETURN
			IF([%ABANDONADAS]=0, BLANK(),a)
			
			```
		displayFolder: Desvio
		lineageTag: ef342206-5681-41eb-95bb-ee9cd7184082

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '@NS CAPA' = 0.9
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: bfa98c87-231c-46e9-8337-93be61f60776

	measure '@ABANDONO CAPA' = 0.005
		displayFolder: Forecast
		lineageTag: 0b2dd576-b280-485e-b469-e637c6833f0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dia da Semana Mais Ligações' = ```
			
			VAR VolumePorIntervalo =
			    SUMMARIZE(
			        '!DIM_CALENDARIO',
			        '!DIM_CALENDARIO'[Dia da Semana],
			        "TotalRecebidas", 
			        [RECEBIDAS]
			    )
			VAR IntervaloComMaiorVolume = 
			    TOPN(1, VolumePorIntervalo, [TotalRecebidas], DESC)
			RETURN
			    MAXX(IntervaloComMaiorVolume, '!DIM_CALENDARIO'[Dia da Semana])
			```
		displayFolder: Telefonia
		lineageTag: 799e8bb6-d523-4c52-9944-eb21f482c57f

	measure 'ABANDONADAS até 10s Total' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 10)
			
			
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 72989b5b-21a0-4bbf-ba7b-db37d61d714b

	measure 'Horário Mais Ligações' = ```
			
			VAR VolumePorIntervalo =
			    SUMMARIZE(
			        '!DIM_CALENDARIO',
			        '!DIM_CALENDARIO'[Intervalo Hora],
			        "TotalRecebidas", 
			        [RECEBIDAS]
			    )
			VAR IntervaloComMaiorVolume = 
			    TOPN(1, VolumePorIntervalo, [TotalRecebidas], DESC)
			RETURN
			    MAXX(IntervaloComMaiorVolume, '!DIM_CALENDARIO'[Intervalo Hora])
			```
		displayFolder: Telefonia
		lineageTag: 0e4b0d49-40d0-4d45-bd5e-836683d9f253

	measure 'Média Atendidas 2.0' = ```
			
			VAR DiasRelevantes = 
			    FILTER(
			        SUMMARIZE(
			            '!DIM_CALENDARIO',
			            '!DIM_CALENDARIO'[Date],
			            '!DIM_CALENDARIO'[Dia da Semana]
			        ),
			        [RECEBIDAS] > 0
			    )
			RETURN
			DIVIDE(
			    [RECEBIDAS],
			    COUNTROWS(DiasRelevantes),
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 41c36d48-73f4-45c2-af9d-31912311a76c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TA = DIVIDE([ABANDONADAS Acima 10s],[RECEBIDAS], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 29b3ef8d-5445-40cb-ab5e-a36ea2b6646a

	measure @TME = 20
		formatString: 0
		displayFolder: Forecast
		lineageTag: 4c7630ac-c6f6-4eca-887c-015127bd460b

	measure %TME =
			
			
			VAR A = DIVIDE([TME],[@TME],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TME]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 32b3f849-31e9-4848-91ba-62408d4004c6

	measure @TMA = 360
		formatString: 0
		displayFolder: Forecast
		lineageTag: 65551e41-2744-409e-af16-11041ae9d7ee

	measure %TMA =
			
			
			VAR A = DIVIDE([TMA],[@TMA],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TMA]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 242a5fd9-9964-40d5-8c15-f982b2216680

	measure @ABANDONO = 0.05
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: 5738a04a-abf6-457a-8382-2dc5fe22ca83

	measure %ABANDONO =
			
			
			VAR A = DIVIDE([%ABANDONADAS],[@ABANDONO],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@ABANDONO]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 5febb5d4-28a5-4c7a-b56c-95e67a33987f

	measure ID =
			
			SWITCH(TRUE(),
			SUM(AVAYA_FT_ATENDIDAS[ID]) = BLANK(), SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),
			SUM(AVAYA_FT_ATENDIDAS[ID])
			)
		displayFolder: Telefonia
		lineageTag: 273ca9d4-ebf3-4163-b85f-109504a3000c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure @TA = 0.03
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: 2d9c772c-5acd-472d-9585-06183cf98709

	measure 'Media Qualidade' = AVERAGE(FT_QUALIDADE_LLM[Nota Final])
		displayFolder: Qualidade
		lineageTag: e2aec183-da31-4e27-a536-28df2b71a2b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtde Avaliacoes' = COUNTROWS(FT_QUALIDADE_LLM)
		formatString: 0
		displayFolder: Qualidade
		lineageTag: d55291bc-f1e8-477f-af52-a03d0f914fe2

	measure 'Qtde NCG' = CALCULATE(COUNT(FT_QUALIDADE_LLM[Tipo]), FT_QUALIDADE_LLM[Tipo] = "NCG")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 176a7b77-65e8-4fd6-8575-30233093616d

	measure 'Qtde NC' = CALCULATE(COUNT(FT_QUALIDADE_LLM[Tipo]), FT_QUALIDADE_LLM[Tipo] = "NC")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: b53e45c9-a9bf-40b1-a68d-f020c5680e47

	measure 'Qtde Nota Max' = CALCULATE(COUNT(FT_QUALIDADE_LLM[Tipo]), FT_QUALIDADE_LLM[Tipo] = "Nota Máxima")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 8f5ba837-aaa3-4e15-8e68-9ad701315e7a

	measure 'Peso Unit' = AVERAGE(FT_OFENSORES_LLM[Peso])
		formatString: 0
		displayFolder: Qualidade
		lineageTag: d5bd8a61-30da-4dbe-a596-04d1f62de2c5

	measure 'Qtde x Peso' = [Qtde Avaliacoes] * [Peso Unit]
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 06793dbf-d6fb-430b-9bbe-4824b73cf188

	measure 'Peso Não Capturado' = DISTINCTCOUNT(FT_OFENSORES_LLM[TAG]) * [Peso Bloco]
		displayFolder: Qualidade
		lineageTag: 7d6638bc-52c5-46f4-9df8-2aea97c8787a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Media Ating. Blocos' = (COUNTROWS(FT_QUALIDADE_LLM)-DISTINCTCOUNT(FT_OFENSORES_LLM[TAG]))/COUNTROWS(FT_QUALIDADE_LLM)
		displayFolder: Qualidade
		lineageTag: bee36c7a-348f-4691-9700-f0fe6cfdc3ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Média Ating. Blocos de Critérios' = ```
			
			VAR MEDIA_ATING_BLOCOS = (COUNTROWS(FT_QUALIDADE_LLM)-COUNT(FT_OFENSORES_LLM[TAG]))/COUNTROWS(FT_QUALIDADE_LLM)
			
			RETURN
			
			CALCULATE(MEDIA_ATING_BLOCOS,
			    FILTER(FT_OFENSORES_LLM, FT_OFENSORES_LLM[Bloco] = SELECTEDVALUE(FT_OFENSORES_LLM[Bloco]))
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: 9dfb005f-e6eb-48a3-b32b-1d135e1564c6

	measure 'Peso Bloco' = MAX(FT_OFENSORES_LLM[Peso])
		displayFolder: Qualidade
		lineageTag: 424c0a3d-750e-46a3-915f-32df013ea120

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Despontuações' = COUNT(FT_OFENSORES_LLM[TAG])
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 6e28c0e0-bd6e-481f-86dc-329680ec3cb2

	measure 'Despontuações NC' = CALCULATE(COUNT(FT_OFENSORES_LLM[TAG]), FT_OFENSORES_LLM[NCG] = "Não")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 49ff9156-3652-4cd9-aa48-ec15feadb166

	measure 'Despontuações NCG' = CALCULATE(COUNT(FT_OFENSORES_LLM[TAG]), FT_OFENSORES_LLM[NCG] = "Sim")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 3bc11dad-d339-4247-a31b-d9b9306886cd

	measure 'Índice Não Conf. no Atend.' =
			
			VAR Qtd_INA = CALCULATE(COUNT(FT_QUALIDADE_LLM[Status Nota]), FT_QUALIDADE_LLM[Status Nota] <> "Nota Máxima")
			VAR Total_Aval = COUNTROWS(FT_QUALIDADE_LLM)
			
			RETURN
			
			DIVIDE(Qtd_INA,Total_Aval, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: 2341cbf6-3c65-44df-bd67-4bcaa7d7bb0f

	measure 'Evolução NS Realizado' = ```
			
			VAR ParamData = SELECTEDVALUE('Parâmetro_Data'[Parâmetro])
			
			VAR OrdemAtual = MAX('Ultimos3MesesTabela'[OrdemData])
			
			VAR ValorAtual = [NS Realizado]
			
			VAR ValorAnterior =
			    CALCULATE(
			        [NS Realizado],
			        FILTER(
			            ALL('Ultimos3MesesTabela'),
			            'Ultimos3MesesTabela'[OrdemData] = OrdemAtual - 1
			        )
			    )
			
			RETURN
			IF(
			    ValorAtual = 0 || ValorAtual = ValorAnterior || ISBLANK(ValorAnterior),
			    BLANK(),
			    DIVIDE(ValorAtual - ValorAnterior, ValorAnterior)
			)
			
			```
		displayFolder: Telefonia
		lineageTag: 3874f432-3c90-4650-a692-2a00368e894a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Evolução TMO' = ```
			
			VAR ParamData = SELECTEDVALUE('Parâmetro_Data'[Parâmetro])
			
			VAR OrdemAtual = MAX('Ultimos3MesesTabela*'[OrdemData])
			
			VAR ValorAtual = [TMO]
			
			VAR ValorAnterior =
			    CALCULATE(
			        [TMO],
			        FILTER(
			            ALL('Ultimos3MesesTabela*'),
			            'Ultimos3MesesTabela*'[OrdemData] = OrdemAtual - 1
			        )
			    )
			
			RETURN
			IF(
			    ValorAtual = 0 || ValorAtual = ValorAnterior || ISBLANK(ValorAnterior),
			    BLANK(),
			    DIVIDE(ValorAtual - ValorAnterior, ValorAnterior)
			)
			
			```
		displayFolder: Telefonia
		lineageTag: c74cbf75-2040-48e5-8eb1-841804c8e3c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '*% Satisfeitos' = [*Qtde. Satisfeitos]/[*Qtde. Pesquisas]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 71f52338-be22-42b3-a914-1d59365e7968

	measure '*% Insatisfeitos' = [*Qtde. Insatisfeitos]/[*Qtde. Pesquisas]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: a818dace-c863-4bbb-be73-bc6c5db373f7

	measure '*Qtde. Satisfeitos' = CALCULATE(COUNT(GENESYS_FT_CSAT[SCORE]), GENESYS_FT_CSAT[SCORE] >=3)
		formatString: 0
		displayFolder: NPS
		lineageTag: 55517032-5556-4d1d-9918-23f57440d1d0

	measure '*Qtde. Insatisfeitos' = CALCULATE(COUNT(GENESYS_FT_CSAT[SCORE]), GENESYS_FT_CSAT[SCORE] <=1)
		formatString: 0
		displayFolder: NPS
		lineageTag: 172b0525-ea6b-4fbc-998b-422f11ce21f6

	measure '*Qtde. Pesquisas' = COUNTROWS(GENESYS_FT_CSAT)
		formatString: 0
		displayFolder: NPS
		lineageTag: 7d46fe79-77d8-4268-ba02-31a8db708051

	measure '% IAF' = IFERROR([IAF]/[RECEBIDAS],0) --% DE DESCONEXÃO
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 9654ce57-4c8f-45f6-b973-79c2dc769c85

	measure IAF =
			
			VAR Desconexoes = COUNTROWS('GENESYS_FT_DESCONEXÃO')
			
			RETURN
			
			IF(Desconexoes = BLANK(), 0, Desconexoes)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: e961d80a-9411-4cda-93dd-ea8696d0f83b

	measure @SATISFACAO = 0.85
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 193b443e-057b-495d-afed-dcbabc3650d2

	measure @INSATISFACAO = 0.02
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 2c2ac540-e0a3-45ec-9697-e81886a0f2ce

	measure '% Satisf. Proj.' =
			
			VAR SATISFEITOS = [*% Satisfeitos]
			VAR META_SATISFEITOS = [@SATISFACAO]
			VAR DESVIO_SATISFEITOS = DIVIDE(SATISFEITOS, META_SATISFEITOS, 0)
			
			RETURN
			IF(DESVIO_SATISFEITOS = 0, 0, DESVIO_SATISFEITOS - 1)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 7c199cfd-8ac8-48db-a19d-a36d0b445c2b

	measure '% Insatisf. Proj.' =
			
			VAR INSATISFEITOS = [*% Insatisfeitos]
			VAR META_INSATISFEITOS = [@INSATISFACAO]
			VAR DESVIO_INSATISFEITOS = DIVIDE(INSATISFEITOS, META_INSATISFEITOS, 0)
			
			RETURN
			IF(DESVIO_INSATISFEITOS = 0, 0, DESVIO_INSATISFEITOS - 1)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: ce78c283-09e7-4cdb-9ea9-d969468191d0

	measure REGISTROS = SUM(GENESYS_TABULACOES[CONTAGEM])
		formatString: 0
		displayFolder: Registros
		lineageTag: a5a0dbe1-95cf-4bc7-80c1-d28c8ccb01e9

	measure %REGISTROS = [REGISTROS]/[ATENDIDAS]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Registros
		lineageTag: 9f9d3d95-d714-4da3-aa3e-60b3be037519

	measure PA_Base =
			
			
			VAR MaxGenesys = MAX(GENESYS_FT_PAUSAS[CONTA PA])
			RETURN
			SWITCH(
			    TRUE(),
			   MaxGenesys = 0, BLANK(),
			   MaxGenesys
			)
		displayFolder: Tempos
		lineageTag: 1734f00d-ab50-4194-83c5-d1b90d3c94b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PA_ATENDIMENTO_08000 =
			
			CALCULATE(
			    [PA_Base],
			    REMOVEFILTERS('!DIM_SKILL'),
			    FILTER(
			        ALL('!DIM_SKILL'),
			        TRIM(UPPER('!DIM_SKILL'[FILTRO])) = "ATENDIMENTO 08000"
			    )
			)
		displayFolder: Tempos
		lineageTag: aea64130-bb7c-44f3-9e16-6f040fa37850

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PA_EMERGENCIA_OBRAS =
			
			CALCULATE(
			    [PA_Base],
			    REMOVEFILTERS('!DIM_SKILL'),
			    FILTER(
			        ALL('!DIM_SKILL'),
			        TRIM(UPPER('!DIM_SKILL'[FILTRO])) = "EMERGENCIA + OBRAS"
			    )
			)
		displayFolder: Tempos
		lineageTag: 8578d4b5-2674-46f8-a58c-41248a912285

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PA_08000_CONTAS =
			
			CALCULATE(
			    [PA_Base],
			    REMOVEFILTERS('!DIM_SKILL'),
			    FILTER(
			        ALL('!DIM_SKILL'),
			        TRIM(UPPER('!DIM_SKILL'[FILTRO])) = "08000 CONTAS"
			    )
			)
		displayFolder: Tempos
		lineageTag: a9a4fbd3-9e4e-4bfb-ab9d-a4e2944f53fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PA_Report =
			
			var pa_genesys = MAX(GENESYS_FT_PAUSAS[CONTA PA])
			
			
			RETURN
			
			pa_genesys
		formatString: 0
		displayFolder: Tempos
		lineageTag: b5d3488b-ae21-49cf-9808-b7158c6620ad

	measure %PA_Report =
			
			
			VAR A = DIVIDE([PA_Report],[@PA],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@PA]), BLANK(),
			    [@PA] = 0, BLANK(), A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: b3234cdc-aabd-4698-9de4-07a97b353553

	measure Comparativo_Recebidas_D-1 = ```
			
			VAR _DiaAtual =
			    CALCULATE(
			        MAX('!DIM_CALENDARIO'[Data]),
			        FILTER('!DIM_CALENDARIO', [Status Dia] = "Dia Atual")
			    )
			VAR _DiaAnterior = _DiaAtual - 1
			VAR _ValorAtual =
			    CALCULATE(
			        [RECEBIDAS],
			        FILTER(ALL('!DIM_CALENDARIO'), '!DIM_CALENDARIO'[Data] = _DiaAtual)
			    )
			VAR _ValorAnterior =
			    CALCULATE(
			        [RECEBIDAS],
			        FILTER(ALL('!DIM_CALENDARIO'), '!DIM_CALENDARIO'[Data] = _DiaAnterior)
			    )
			RETURN
			IF(
			    NOT ISBLANK(_ValorAtual) && NOT ISBLANK(_ValorAnterior),
			    DIVIDE(_ValorAtual, _ValorAnterior) - 1,
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: ef6ae9a3-dac4-4bcb-8a1f-0ea20c1ff400

	measure Comparativo_Recebidas_D-7 = ```
			
			VAR _DiaAtual =
			    CALCULATE(
			        MAX('!DIM_CALENDARIO'[Data]),
			        FILTER('!DIM_CALENDARIO', [Status Dia] = "Dia Atual")
			    )
			VAR _Dia7Atras = _DiaAtual - 7
			VAR _ValorAtual =
			    CALCULATE(
			        [RECEBIDAS],
			        FILTER(ALL('!DIM_CALENDARIO'), '!DIM_CALENDARIO'[Data] = _DiaAtual)
			    )
			VAR _Valor7Atras =
			    CALCULATE(
			        [RECEBIDAS],
			        FILTER(ALL('!DIM_CALENDARIO'), '!DIM_CALENDARIO'[Data] = _Dia7Atras)
			    )
			RETURN
			IF(
			    NOT ISBLANK(_ValorAtual) && NOT ISBLANK(_Valor7Atras),
			    DIVIDE(_ValorAtual, _Valor7Atras) - 1,
			    BLANK()
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 2395bc1f-0f17-4610-a513-1c168224977a

	measure 'DMM Sem Total' =
			
			IF(
			    HASONEVALUE('@FT_FORECAST'[DMM ORDEM Matriz]),  // Mostra apenas quando há contexto específico
			    MAX('@FT_FORECAST'[DMM ORDEM Matriz]),
			    BLANK()
			)
		lineageTag: 9840ea83-4946-412e-8639-149072c902fa

	measure '@HC Bruto Previsto' =
			
			SWITCH(TRUE(),
			ISBLANK([@HORAS CONTRATADAS]), BLANK(),
			MAX('@FT_FORECAST'[HC BRUTO Acumulado]))
		formatString: 0
		lineageTag: 09a1f943-29e6-41af-9847-94a7608e859d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '%HC Bruto' =
			
			
			VAR A = DIVIDE([HC Bruto],[@HC Bruto Previsto],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@HORAS CONTRATADAS]),BLANK(),
			    ISBLANK([@HC Bruto Previsto]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2cf697d3-99c6-4780-8b75-e5f61a27fae8

	measure Tooltip_Analise = ```
			
			VAR Tipo = SELECTEDVALUE(Dim_Tooltip[TooltipID])
			VAR NS = [NS Realizado]
			VAR MetaNS = 0.9
			VAR Abandono = [%ABANDONADAS]
			VAR MetaAbandono = 0.05
			VAR TMO = [TMO]
			VAR MetaTMO = 542
			VAR Recebidas = [RECEBIDAS]
			VAR ForecastRecebidas = [@RECEBIDAS]
			VAR Atendidas = [ATENDIDAS]
			VAR ForecastAtendidas = [@ATENDIDAS]
			VAR PAsLogadas = [%PA]
			VAR ForecastPAs = [@PA]
			
			RETURN
			SWITCH(
			    TRUE(),
			
			    -- =========================
			    -- TOOLTIP NS
			    -- =========================
			    Tipo = "NS",
			        IF(
			            ISBLANK(NS),
			            "ℹ️ Nível de Serviço" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            SWITCH(
			                TRUE(),
			
			                NS >= MetaNS,
			                "🟢 Nível de Serviço dentro da meta" & UNICHAR(10) & UNICHAR(10) &
			                "O NS atual está em " & FORMAT(NS, "0.00%") &
			                ", acima da meta de 90,00%." & UNICHAR(10) &
			                "O tempo de espera está adequado para o cliente." & UNICHAR(10) &
			                "Recomendação: manter o dimensionamento atual.",
			
			                NS >= 0.85,
			                "🟡 Nível de Serviço em alerta" & UNICHAR(10) & UNICHAR(10) &
			                "O NS atual está em " & FORMAT(NS, "0.00%") &
			                ", abaixo da meta de 90,00%." & UNICHAR(10) &
			                "Há aumento perceptível no tempo de espera." & UNICHAR(10) &
			                "Recomendação: revisar escala e aderência.",
			
			                "🔴 Nível de Serviço crítico" & UNICHAR(10) & UNICHAR(10) &
			                "O NS atual está em " & FORMAT(NS, "0.00%") &
			                ", muito abaixo da meta de 90,00%." & UNICHAR(10) &
			                "Impacto direto na experiência do cliente." & UNICHAR(10) &
			                "Recomendação: reforçar atendimento imediatamente."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP ABANDONO
			    -- =========================
			    Tipo = "ABANDONO",
			        IF(
			            ISBLANK(Abandono),
			            "ℹ️ Abandono" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            SWITCH(
			                TRUE(),
			
			                Abandono <= MetaAbandono,
			                "🟢 Abandono dentro da meta" & UNICHAR(10) & UNICHAR(10) &
			                "O abandono está em " & FORMAT(Abandono, "0.00%") &
			                ", dentro da meta operacional de até 5,00%." & UNICHAR(10) &
			                "O tempo de espera está adequado e a retenção é satisfatória." & UNICHAR(10) &
			                "Recomendação: manter o dimensionamento atual.",
			
			                Abandono <= 0.08,
			                "🟡 Abandono em nível de atenção" & UNICHAR(10) & UNICHAR(10) &
			                "O abandono está em " & FORMAT(Abandono, "0.00%") &
			                ", acima da meta de 5,00%." & UNICHAR(10) &
			                "Há indícios de aumento no tempo de espera ou filas." & UNICHAR(10) &
			                "Recomendação: revisar picos de demanda e aderência.",
			
			                "🔴 Abandono crítico" & UNICHAR(10) & UNICHAR(10) &
			                "O abandono está em " & FORMAT(Abandono, "0.00%") &
			                ", muito acima da meta de 5,00%." & UNICHAR(10) &
			                "Clientes estão desistindo antes do atendimento." & UNICHAR(10) &
			                "Recomendação: reforçar escala e priorizar filas críticas."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP TMO
			    -- =========================
			    Tipo = "TMO",
			        IF(
			            ISBLANK(TMO),
			            "ℹ️ TMO" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            SWITCH(
			                TRUE(),
			
			                TMO <= MetaTMO,
			                "🟢 TMO dentro da meta" & UNICHAR(10) & UNICHAR(10) &
			                "O TMO está em " & FORMAT(TMO, "0") &
			                ", dentro da meta operacional de até " & MetaTMO & "." & UNICHAR(10) &
			                "O TMO está controlado e compatível com o forecast." & UNICHAR(10) &
			                "Recomendação: manter a eficiência e qualidade.",
			
			                TMO <= MetaTMO * 1.1,
			                "🟡 TMO em nível de atenção" & UNICHAR(10) & UNICHAR(10) &
			                "O TMO está em " & FORMAT(TMO, "0") &
			                ", acima da meta de " & MetaTMO & "." & UNICHAR(10) &
			                "Pode indicar dificuldade operacional ou falhas de script." & UNICHAR(10) &
			                "Recomendação: Monitorar causas.",
			
			                "🔴 TMO crítico" & UNICHAR(10) & UNICHAR(10) &
			                "O TMO está em " & FORMAT(TMO, "0") &
			                ", muito acima da meta de " & MetaTMO & "." & UNICHAR(10) &
			                "Impacto no NS e no Abandono." & UNICHAR(10) &
			                "Recomendação: Revisar processos, scripts, sistemas e capacitação."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP VOLUME RECEBIDO
			    -- =========================
			    Tipo = "VOLUME_RECEBIDO",
			        IF(
			            ISBLANK(Recebidas),
			            "ℹ️ Volume Recebido" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            "📞 Volume Recebido" & UNICHAR(10) & UNICHAR(10) &
			            "Foram recebidas " & FORMAT(Recebidas, "0") & " chamadas no período." & UNICHAR(10) &
			            "O impacto operacional depende da capacidade disponível." & UNICHAR(10) &
			            "Recomendação: analisar em conjunto com NS, Abandono e PAs logadas."
			        ),
			
			    -- =========================
			    -- TOOLTIP VOLUME ATENDIDO
			    -- =========================
			    Tipo = "VOLUME_ATENDIDO",
			        IF(
			            ISBLANK(Atendidas),
			            "ℹ️ Volume Atendido" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            VAR TaxaAtendimento = DIVIDE(Atendidas, Recebidas)
			
			            RETURN
			            SWITCH(
			                TRUE(),
			
			                TaxaAtendimento >= 0.95,
			                "🟢 Volume Atendido adequado" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(Atendidas, "0") & " chamadas atendidas." & UNICHAR(10) &
			                "Alta taxa de absorção da demanda." & UNICHAR(10) &
			                "Recomendação: manter capacidade atual.",
			
			                TaxaAtendimento >= 0.90,
			                "🟡 Volume Atendido em atenção" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(Atendidas, "0") & " chamadas atendidas." & UNICHAR(10) &
			                "Parte da demanda não está sendo absorvida." & UNICHAR(10) &
			                "Recomendação: revisar escala e TMO.",
			
			                "🔴 Volume Atendido crítico" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(Atendidas, "0") & " chamadas atendidas." & UNICHAR(10) &
			                "Baixa capacidade frente à demanda." & UNICHAR(10) &
			                "Recomendação: reforçar PAs e reduzir tempo médio."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP PAs LOGADAS
			    -- =========================
			    Tipo = "PAS",
			        IF(
			            ISBLANK(PAsLogadas),
			            "ℹ️ PAs Logadas" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            VAR AderenciaPA = DIVIDE(PAsLogadas, ForecastPAs)
			
			            RETURN
			            SWITCH(
			                TRUE(),
			
			                AderenciaPA >= 0.95,
			                "🟢 PAs dentro do planejado" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(PAsLogadas, "0") & " PAs logadas." & UNICHAR(10) &
			                "A escala está sendo cumprida adequadamente." & UNICHAR(10) &
			                "Recomendação: manter gestão atual.",
			
			                AderenciaPA >= 0.85,
			                "🟡 PAs em nível de atenção" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(PAsLogadas, "0") & " PAs logadas." & UNICHAR(10) &
			                "Déficit parcial de operadores." & UNICHAR(10) &
			                "Recomendação: verificar faltas, pausas e aderência.",
			
			                "🔴 PAs críticas" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(PAsLogadas, "0") & " PAs logadas." & UNICHAR(10) &
			                "Déficit severo de capacidade operacional." & UNICHAR(10) &
			                "Recomendação: acionar contingência e replanejar escala."
			            )
			        ),
			 
			
			    -- FALLBACK
			    "ℹ️ Indicador não identificado"
			)
			
			```
		displayFolder: INTELIGENTE
		lineageTag: 47a0f797-1ef4-4cc7-8837-dc4cf464c466

	column Column
		isHidden
		formatString: 0
		lineageTag: e4da24e7-a23d-4f89-83e6-e5f62f6f1205
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition !Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 3e1c8ff410e1421897d7da13d3b8f2c3

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

