table GENESYS_FT_ATENDIDAS
	lineageTag: 94fc4ec4-8546-47ec-a827-19c584e6483d

	column ROUTING_SKILL_NAME
		dataType: string
		lineageTag: 0061ce28-b9c8-4397-b017-d9bb2b62c529
		summarizeBy: none
		sourceColumn: ROUTING_SKILL_NAME

		annotation SummarizationSetBy = Automatic

	column DIVISION_NAME
		dataType: string
		lineageTag: 39181797-507c-49f4-91a4-7d513980adae
		summarizeBy: none
		sourceColumn: DIVISION_NAME

		annotation SummarizationSetBy = Automatic

	column ATENDIDAS
		dataType: double
		lineageTag: 2936f529-1226-4ff2-a174-cc4d41389048
		summarizeBy: sum
		sourceColumn: ATENDIDAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ANSWERED_TIME
		dataType: double
		lineageTag: fb137eb9-0888-4a51-b207-958f360d82a9
		summarizeBy: sum
		sourceColumn: ANSWERED_TIME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TALK_COMPLETE_TIME
		dataType: double
		lineageTag: f59e6b7c-4375-4aa9-b261-2bb62310079e
		summarizeBy: sum
		sourceColumn: TALK_COMPLETE_TIME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ACW_TIME
		dataType: double
		lineageTag: 56463b01-fa81-4479-9942-f7a7429e2f1d
		summarizeBy: sum
		sourceColumn: ACW_TIME

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DATA HORA'
		dataType: dateTime
		formatString: General Date
		lineageTag: 867d4216-ba4f-4975-a2bf-a10583957cea
		summarizeBy: none
		sourceColumn: DATA HORA

		variation Variation
			isDefault
			relationship: 825ca3a2-a7fa-475a-bb9d-ae0fac02694a
			defaultHierarchy: LocalDateTable_3619d1dc-9331-49f3-9011-baf4ccd746cd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column STATUS_ATENDIDAS = ```
			
			
			
			SWITCH(TRUE(),
			
			GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 5,       "Atendidas até 5",
			GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 10 ,     "Atendidas até 10",
			GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 15,      "Atendidas até 15",
			GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 20,      "Atendidas até 20",
			GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 25,      "Atendidas até 25",
			"Acima de 25")
			
			```
		lineageTag: 32d4dd49-8bda-49d7-8bc9-d814d91234a5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TEMPO_OPERACIONAL = GENESYS_FT_ATENDIDAS[TALK_COMPLETE_TIME] + GENESYS_FT_ATENDIDAS[ACW_TIME]
		lineageTag: 7fd7f340-daf4-477a-bddb-c376bddb359b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MD
		dataType: string
		lineageTag: 7930194d-69ce-42ac-acae-f5535a9e8c3c
		summarizeBy: none
		sourceColumn: MD

		annotation SummarizationSetBy = Automatic

	column CHAVE_INTERVALO = FORMAT(GENESYS_FT_ATENDIDAS[DATA HORA], "DD/MM/YYYY HH:MM:SS")
		lineageTag: 95fbbb38-b30b-4304-9657-74f376fcd419
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: a44b43ff-3f69-4820-b99d-b88bb778ba6a
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column ROW_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: df7f6415-e382-4794-96d6-c0fc3bebcc6c
		summarizeBy: none
		sourceColumn: ROW_DATE

		variation Variation
			isDefault
			relationship: 9939c99f-adff-4e13-a23f-5819cf141d28
			defaultHierarchy: LocalDateTable_c5e67cb0-4681-49c7-98ed-d5ff01e0f28f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column STARTTIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f70ab5b-3fa1-44f7-8c59-81814b3a88da
		summarizeBy: none
		sourceColumn: STARTTIME

		variation Variation
			isDefault
			relationship: 7323d0fe-05e0-41a2-978b-c43acd7cf454
			defaultHierarchy: LocalDateTable_06038c84-2de3-4e63-a982-553e0076018f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column QUEUE_NAME
		dataType: string
		lineageTag: 447a0d65-c36c-4e85-8973-708fcd128eaa
		summarizeBy: none
		sourceColumn: QUEUE_NAME

		annotation SummarizationSetBy = Automatic

	column SKILL_NUM
		dataType: string
		lineageTag: ef614133-f07f-454e-ac5a-98451d51c293
		summarizeBy: none
		sourceColumn: SKILL_NUM

		annotation SummarizationSetBy = Automatic

	column data_atualizacao
		dataType: dateTime
		formatString: Long Date
		lineageTag: 418a3a07-735a-4fa6-a7f9-9a32322282ad
		summarizeBy: none
		sourceColumn: data_atualizacao

		variation Variation
			isDefault
			relationship: c059bab3-331a-42e8-ad69-3b8bf218e1bf
			defaultHierarchy: LocalDateTable_fc17024d-b566-408a-ae60-3ef8fdc5d7b4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition GENESYS_FT_ATENDIDAS = m
		mode: import
		queryGroup: 'FT D0 + D-1'
		source =
				let
				    Fonte = Table.Combine({#"FT_ATENDIDAS_D-1", #"FT_ATENDIDAS_D-0"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Fonte", each [DATA HORA] >= #"DATA INICIO GENESYS")
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

