table GENESYS_FT_RECEBIDAS
	lineageTag: 4eb3dc95-7928-44f5-9e7c-21ba9c84a1a3

	column ROW_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: 348cdd7f-9151-4547-9a3e-0cb0e54625ec
		summarizeBy: none
		sourceColumn: ROW_DATE

		variation Variation
			isDefault
			relationship: 36d593b5-7bfe-47b6-9d51-a95c620d2746
			defaultHierarchy: LocalDateTable_f6847cb7-879d-4e3d-816d-90d3206aa8b4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column STARTTIME
		dataType: dateTime
		formatString: General Date
		lineageTag: b4fe8efa-8c09-4a6a-ab50-452c104e621b
		summarizeBy: none
		sourceColumn: STARTTIME

		variation Variation
			isDefault
			relationship: 74b3cd8f-73f1-4d57-981e-96c3707104b5
			defaultHierarchy: LocalDateTable_3f6a5c98-5043-43d6-85e7-8de7de46b8b6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DIVISION_NAME
		dataType: string
		lineageTag: 96a8879d-4e92-4932-b40c-09e791b8b22b
		summarizeBy: none
		sourceColumn: DIVISION_NAME

		annotation SummarizationSetBy = Automatic

	column QUEUE_NAME
		dataType: string
		lineageTag: af786762-6f15-45e9-b5d3-189d6eb63fc3
		summarizeBy: none
		sourceColumn: QUEUE_NAME

		annotation SummarizationSetBy = Automatic

	column ROUTING_SKILL_NAME
		dataType: string
		lineageTag: 25bf5f1e-9fcd-42df-b71f-aec081758a8a
		summarizeBy: none
		sourceColumn: ROUTING_SKILL_NAME

		annotation SummarizationSetBy = Automatic

	column SKILL_NUM
		dataType: string
		lineageTag: 46500f44-362f-4389-943e-715f0d6c2497
		summarizeBy: none
		sourceColumn: SKILL_NUM

		annotation SummarizationSetBy = Automatic

	column RECEBIDAS
		dataType: double
		lineageTag: 5039735b-3bac-4434-b1d3-9077b6b3940a
		summarizeBy: sum
		sourceColumn: RECEBIDAS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DATA HORA'
		dataType: dateTime
		formatString: General Date
		lineageTag: c669bbe5-7b87-45ba-a056-29fdefe1c1fd
		summarizeBy: none
		sourceColumn: DATA HORA

		variation Variation
			isDefault
			relationship: 89762b28-fab7-41c7-a18b-18c4cdc6f1aa
			defaultHierarchy: LocalDateTable_a19833d2-598c-45d4-b4aa-a201b4e2452d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column CHAVE_INTERVALO = FORMAT('GENESYS_FT_RECEBIDAS'[DATA HORA], "DD/MM/YYYY HH:MM:SS")
		lineageTag: a6bcd55b-c265-40a5-a4c5-32fbb14ff197
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: b609b12b-1640-4fc4-a411-ad09ec7de388
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column MD
		dataType: string
		lineageTag: 933cfc51-6ba3-4492-b9cc-5c37b64acd73
		summarizeBy: none
		sourceColumn: MD

		annotation SummarizationSetBy = Automatic

	column data_atualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c3b2e03-efbe-4565-9846-61d4e400d5c6
		summarizeBy: none
		sourceColumn: data_atualizacao

		variation Variation
			isDefault
			relationship: 2d5d977c-a56d-4b07-859b-2385e67ce843
			defaultHierarchy: LocalDateTable_0961c1bb-f92d-4d49-8615-335cea21376e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	partition GENESYS_FT_RECEBIDAS = m
		mode: import
		queryGroup: 'FT D0 + D-1'
		source =
				let
				    Fonte = Table.Combine({#"FT_RECEBIDAS_D-1", #"FT_RECEBIDAS_D-0"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Fonte", each [DATA HORA] >= #"DATA INICIO GENESYS")
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

