table !Medidas
	lineageTag: 48ad387a-7da0-4a39-962d-45a26ab2282a

	measure Atualização =
			//"Atualizado em: " & SELECTEDVALUE('Dim_Atualização'[Data e Hora Certa]) & ", com dados até: " & MAX(SUA TABELA)
			
			"Atualizado em: " & SELECTEDVALUE('!DIM_ATUALIZAÇÃO'[Data e Hora Certa]) & ", com dados até: " & CALCULATE(MAX('@FT_FORECAST'[Data]), '!DIM_CALENDARIO'[Intervalo_Status] = 1, REMOVEFILTERS())
		displayFolder: Atualização
		lineageTag: 1795c91e-a257-412b-a497-bd8ed9337c7c

	measure ATENDIDAS =
			
			
			VAR GENESYS = SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS])
			
			RETURN
			
			GENESYS
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 4bc9fc38-539f-4a3e-a9ab-43b6c7f879bf

	measure TRANSFERIDAS = SUM(GEESYS_FT_TRANSFERIDAS[TOTAL])
		formatString: 0
		displayFolder: Telefonia
		lineageTag: c12b18bf-3ae3-404d-8b0a-0db45c68e2cb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ABANDONADAS =
			
			
			VAR ABN = SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS])
			
			RETURN
			
			IF(ABN=0,BLANK(),ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 9ef906be-c0cf-45df-a221-a96d1296853f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure RECEBIDAS =
			
			
			VAR RECEBIDAS = SUM(GENESYS_FT_RECEBIDAS[RECEBIDAS])
			
			RETURN
			
			IF(RECEBIDAS = 0, BLANK(), RECEBIDAS)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: f0b1a906-c8f7-4a82-9aa3-213b25568d9d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'NS Realizado' =
			
			
			VAR ATENDIDAS_NIVEL = [Atendidas no Nível 20s]
			VAR RECEBIDAS = [RECEBIDAS]
			VAR ABN_20 = [ABANDONADAS até 20s Total]
			
			
			RETURN
			
			DIVIDE(ATENDIDAS_NIVEL,(RECEBIDAS - ABN_20), BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 66335235-1bd9-4dc2-9d5d-2f3aa285c881

	measure TMA =
			
			
			VAR TMA = SUM('GENESYS_FT_FINALIZADAS'[TALK_COMPLETE_TIME])
			VAR atendidas = SUM('GENESYS_FT_FINALIZADAS'[FINALIZADAS])
			VAR calculo = DIVIDE(TMA, ATENDIDAS, BLANK())
			
			RETURN
			    calculo
		formatString: 0
		displayFolder: Telefonia
		lineageTag: ae314a0a-e484-4a4e-8d50-cb633e6f4222

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ContaPA = ```
			
			
			VAR TL = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			
			RETURN  
			
			DIVIDE(TL,1800,BLANK())
			```
		displayFolder: Tempos
		lineageTag: bdacdde9-f6a6-4925-9fd4-db15961e9aad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ContaPA_Max = ```
			
			
			VAR MAXIMO = MAX(GENESYS_FT_PAUSAS[CONTA PA])
			
			RETURN
			
			MAXIMO
			
			```
		formatString: 0
		displayFolder: Tempos
		lineageTag: 8ee1291b-b728-4cd8-bd30-95259c1bd0db

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Atendidas no Nível 20s' = ```
			
			
			VAR GENESYS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 20)
			
			RETURN
			
			GENESYS
			
			```
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 5151db96-c7f3-4b3b-a0e1-3408e9aa1041

	measure TMO =
			
			
			VAR TMO = SUM(GENESYS_FT_FINALIZADAS[TEMPO_OPERACIONAL])
			VAR ATENDIDAS = SUM(GENESYS_FT_FINALIZADAS[FINALIZADAS])
			
			RETURN
			
			DIVIDE( TMO, ATENDIDAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 993e2a91-d4da-4aa7-b635-ed4dd351d6c0

	measure TME =
			
			
			VAR TME = SUM(GENESYS_FT_ATENDIDAS[ANSWERED_TIME])
			VAR ATENDIDAS = [ATENDIDAS]
			
			RETURN
			
			DIVIDE( TME, ATENDIDAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 437022eb-9a5a-4386-8319-d29cb6587c79

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'ABANDONADAS até 20s Total' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 20)
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 0c27fbc3-1188-461e-a511-1ee064be06f2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %ABANDONADAS = DIVIDE([ABANDONADAS], [RECEBIDAS], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: 1d89b687-1602-4c7b-bab4-ef65da8306bf

	measure Trafego =
			
			
			--[ATENDIDAS] * [TMO] + [ABANDONADAS] * [TMABN]
			
			[RECEBIDAS] * [TMO]
		formatString: 0
		displayFolder: Telefonia
		lineageTag: ada682de-8737-42bb-8365-b56ad5758132

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %ATENDIDO = DIVIDE([ATENDIDAS],[RECEBIDAS], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: d4fd3ffc-dd68-40b1-987d-4c5cbff6af95

	measure 'Tempo Logado' = ```
			
			VAR TL = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			
			VAR T =   TL
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			RETURN
			 
			vresultado
			
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: d288af86-ffcf-43dc-9255-a9b81988bc45

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Pausa Total' = ```
			
			
			VAR PAUSAS = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche]) +  SUM(GENESYS_FT_PAUSAS[Treinamento])
			
			VAR T = PAUSAS   
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			RETURN
			 
			vresultado
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: 42732193-d7bf-408e-ad9a-991106ca8170

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Tempo Produtivo' = ```
			
			
			-- TEMPOS GENESYS
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			VAR TEMPO_PAUSAS = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche]) +  SUM(GENESYS_FT_PAUSAS[Treinamento])
			
			VAR TEMPO_PRODUTIVO = TEMPO_LOGADO - TEMPO_PAUSAS
			VAR T =   TEMPO_PRODUTIVO
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			RETURN
			 
			vresultado
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: 960a4197-ed21-4410-8bf0-a54b5ea7b396

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Carga HC' = 22800
		formatString: 0
		displayFolder: Tempos
		lineageTag: d4418ce3-083b-4707-891a-ed5cea432e8d

	measure 'HC Bruto Real Total' =
			
			
			VAR HC = MAXX(GENESYS_FT_PAUSAS, [HC Bruto Real])
			
			// Calcular a razão em relação à carga
			VAR Carga_HC = [Carga HC]
			
			RETURN DIVIDE(HC, Carga_HC, BLANK())
		formatString: 0
		displayFolder: Tempos
		lineageTag: 8592d18b-ecc5-4969-a4f9-bd0ab4573533

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'HC Liquido Real' =
			
			
			VAR HC = MAXX(GENESYS_FT_PAUSAS, [HC_Liq_Real])
			
			// Calcular a razão em relação à carga
			VAR Carga_HC = [Carga HC]
			
			RETURN DIVIDE(HC, Carga_HC, BLANK())
		formatString: 0
		displayFolder: Tempos
		lineageTag: 4ac88930-d39c-4a7a-8cef-9f88b38aa59e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure TMABN =
			
			
			VAR TMABN = SUM(GENESYS_FT_ABANDONADAS[TEMPO_ABANDONO])
			VAR ABANDONADAS = [ABANDONADAS]
			
			RETURN
			
			DIVIDE( TMABN, ABANDONADAS, BLANK())
		formatString: 0
		displayFolder: Telefonia
		lineageTag: a076bf18-6314-4159-a298-789d9131027e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% POCC' =
			
			VAR TrafficInDays = [Trafego]/86400
			VAR AvailableTimeInDays = SUMX(GENESYS_FT_PAUSAS, GENESYS_FT_PAUSAS[Tempo_total] - (GENESYS_FT_PAUSAS[Pausa] + GENESYS_FT_PAUSAS[Lanche] + GENESYS_FT_PAUSAS[Treinamento]))/86400
			VAR RawPercentage = DIVIDE(TrafficInDays, AvailableTimeInDays, 0)
			RETURN
			    IF(RawPercentage > 1, 1, RawPercentage)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Tempos
		lineageTag: b5bfbe47-e6c2-4ef2-9775-f631287a36e0

	measure 'Pausa NR' = ```
			
			
			VAR NR = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche])
			
			VAR T =   NR
			VAR H =   INT(T/3600)
			VAR M =   INT((T - (H * 3600))/60)  
			VAR S =   MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			RETURN
			 
			vresultado
			```
		formatString: 00:00:00
		displayFolder: Tempos
		lineageTag: 22fc4bdd-0bf2-4ee3-81f6-369e0fe0abb6

		annotation PBI_FormatHint = {"isCustom":true}

	measure @RECEBIDAS =
			
			
			VAR A = SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			
			RETURN
			IF(
			    A = 0 || ISBLANK(A),BLANK(), A
			)
		formatString: 0
		displayFolder: Forecast
		lineageTag: 23284297-4a87-432c-855d-327f90a20c88

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @ATENDIDAS = ```
			
			
			
			VAR RECEBIDAS = [@RECEBIDAS]
			VAR FATOR = 0.92
			VAR A = RECEBIDAS * FATOR
			
			
			RETURN
			
			IF(A=0,BLANK(),A)
			
			```
		formatString: 0
		displayFolder: Forecast
		lineageTag: d3fe2680-3f33-4a60-a9c0-e142bdd44728

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @NS = ```
			
			/*
			
			MEDIDA COMPAGAS
			
			VAR TotalPonderado = SUM('@FT_FORECAST'[Nível de Serviço POND])
			VAR VolumeProjetado = SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			RETURN
			IF(
			    ISBLANK(VolumeProjetado) || VolumeProjetado = 0,BLANK(),
			    DIVIDE(
			        TotalPonderado,
			        VolumeProjetado,
			        0
			    )
			)*/
			
			
			-- MEDIDA SULGAS
			VAR TotalPonderado = 
			    SUMX(
			        '@FT_FORECAST',
			        '@FT_FORECAST'[Nível de Serviço PREVISTO] * '@FT_FORECAST'[Chamadas recebidas PREVISTO]
			    )
			VAR VolumeProjetado = 
			    SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			RETURN
			    IF(
			        ISBLANK(VolumeProjetado) || VolumeProjetado = 0,
			        BLANK(),
			        DIVIDE(
			            TotalPonderado,
			            VolumeProjetado,
			            BLANK()
			        )
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: 68c0aec8-3289-48f2-ae2b-4fd56a59753a

	measure 'Atendidas Fora do Nível 20s' = ```
			
			 
			VAR GENESYS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] > 20)
			
			RETURN
			    
			GENESYS
			              
			```
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 39730fb3-7cac-430f-8cd1-c6fcedf54d1b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @PA = MAX('@FT_FORECAST'[RECURSOS PREVISTOS (HC)])
		formatString: 0
		displayFolder: Forecast
		lineageTag: 61e224c6-edbe-447f-937e-7fdc25e37dfe

	measure @TRAFEGO =
			
			
			
			
			SUMX('@FT_FORECAST','@FT_FORECAST'[Chamadas recebidas PREVISTO]*'@FT_FORECAST'[TMO PREVISTO])
		formatString: 0
		displayFolder: Forecast
		lineageTag: 302fb095-348b-4726-82c8-d3c28e592848

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @TMO = ```
			
			 
			VAR TotalTMO = SUM('@FT_FORECAST'[POND TMO PREVISTO])
			VAR TotalChamadas = SUM('@FT_FORECAST'[Chamadas recebidas PREVISTO])
			
			RETURN
			IF(
			    TotalChamadas = 0 || ISBLANK(TotalChamadas),
			    BLANK(),
			    DIVIDE(
			        TotalTMO,
			        TotalChamadas,
			        BLANK()
			    )
			)
			
			```
		formatString: 0
		displayFolder: Forecast
		lineageTag: 29f07a22-b4af-4b45-ba12-faa9a5601125

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '@HC Líquido Previsto' =
			
			
			VAR PAsProjetados = MAX('@FT_FORECAST'[RECURSOS PREVISTOS (HC)])
			VAR CargaHC = [Carga HC]
			VAR TaxaCorrespondente = 1-(([Carga HC]*0.105263)/[Carga HC])
			
			RETURN
			PAsProjetados * TaxaCorrespondente
		formatString: 0
		displayFolder: Forecast
		lineageTag: 23c6ef74-27e0-4c93-93e2-b554d8a05537

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '@HORAS CONTRATADAS' =
			
			VAR T = SUM('@FT_FORECAST'[HORA PREVISTA])*86400
			VAR H = INT(T/3600)
			VAR M = INT((T - (H * 3600))/60)
			VAR S = MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			vresultado
		formatString: 00:00:00
		displayFolder: Forecast
		lineageTag: f295159a-9086-4ffa-83b1-8c4247d30de6

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'ABANDONADAS Acima 20s' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] > 20)
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 8792827d-5bae-4ba3-aad9-da752ba254dc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure @PAUSAS =
			
			VAR T = [@HC Líquido Previsto]*2400
			VAR H = INT(T/3600)
			VAR M = INT((T - (H * 3600))/60)
			VAR S = MOD(t,60)
			VAR vresultado = H * 10000 + M * 100 + S //VALUE(H & M & S)
			
			RETURN
			vresultado
		formatString: 00:00:00
		displayFolder: Forecast
		lineageTag: 0a096740-6e26-434b-b76b-b5b612277d57

		annotation PBI_FormatHint = {"isCustom":true}

	measure %RECEBIDAS =
			
			VAR A = DIVIDE([RECEBIDAS],[@RECEBIDAS], BLANK()) - 1
			
			RETURN
			
			IF(ISBLANK([@RECEBIDAS]) || ISBLANK(A) || A = 0 ,BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: c8537b2c-8216-4967-8491-984c65c9a200

	measure %ATENDIDAS =
			
			VAR A = DIVIDE([atendidas],[@atendidas], BLANK()) - 1
			
			RETURN
			
			 SWITCH(TRUE(),
			     [@atendidas]=0 , BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 86da3880-c0b4-4329-871d-da5c2c35a273

	measure %NS = ```
			
			
			   VAR A = [NS Realizado]-[@NS]
			
			   RETURN
			
			   SWITCH(TRUE(),
			    ISBLANK([NS Realizado]), BLANK(),A)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: fab3d74e-ff86-4098-8d85-50ecf58c8457

	measure %PA =
			
			
			VAR A = DIVIDE([ContaPA_Max],[@PA],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@PA]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: c800fdea-4b1d-4023-bed0-b26b3241aeb5

	measure %TRAFEGO =
			
			
			VAR A = DIVIDE([Trafego],[@TRAFEGO],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TRAFEGO]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 69b521d7-4936-47a0-aa42-fe4a052a2d99

	measure %TMO =
			
			
			VAR A = DIVIDE([TMO],[@TMO],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TMO]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: f3dfffee-af80-454f-a032-c45bc20784c4

	measure %HC =
			
			
			VAR A = DIVIDE([HC Liquido Real],[@HC Líquido Previsto],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@HC Líquido Previsto]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: f73f45ac-ac43-4041-b710-5793a05161a2

	measure '%Tempo Logado' =
			
			
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			VAR A = DIVIDE(TEMPO_LOGADO,SUM('@FT_FORECAST'[HORA PREVISTA])*86400,BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@HORAS CONTRATADAS]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: c3627589-1ed4-4318-9f96-4bb67d8ca4d6

	measure '%Tempo Produtivo' =
			
			
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			VAR TEMPO_PAUSAS = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche]) +  SUM(GENESYS_FT_PAUSAS[Treinamento])
			
			
			VAR TEMPO_PRODUTIVO = TEMPO_LOGADO - TEMPO_PAUSAS
			VAR A = DIVIDE(TEMPO_PRODUTIVO, TEMPO_LOGADO,BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),   ISBLANK([Tempo Logado]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: a04a99df-acc4-497e-aa24-d283c1b78fac

	measure %PAUSA =
			
			
			VAR TEMPO_LOGADO = SUM(GENESYS_FT_PAUSAS[Tempo_total])
			VAR TEMPO_PAUSAS = SUM(GENESYS_FT_PAUSAS[Pausa]) +  SUM(GENESYS_FT_PAUSAS[Lanche]) +  SUM(GENESYS_FT_PAUSAS[Treinamento])
			
			
			VAR TEMPO_PRODUTIVO = TEMPO_LOGADO - TEMPO_PAUSAS
			VAR A = DIVIDE(TEMPO_PAUSAS, TEMPO_LOGADO,BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([Tempo Logado]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 12a7aa60-fa0b-4f88-abe6-58ca8053098c

	measure '%Variação Abandono' = ```
			
			
			var a = [%ABANDONADAS] - 0.05
			
			RETURN
			
			IF([%ABANDONADAS]=0, BLANK(),a)
			
			```
		displayFolder: Desvio
		lineageTag: ef342206-5681-41eb-95bb-ee9cd7184082

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '@NS CAPA' = 0.9
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: bfa98c87-231c-46e9-8337-93be61f60776

	measure '@ABANDONO CAPA' = 0.05
		displayFolder: Forecast
		lineageTag: 0b2dd576-b280-485e-b469-e637c6833f0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ABANDONADAS até 5s' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 5)
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		displayFolder: Telefonia
		lineageTag: 913e78fb-2455-4924-8fad-e168e0bb4ebe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ABANDONADAS até 10s' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] > 5 && GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 10)
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		displayFolder: Telefonia
		lineageTag: acad7d6c-72d4-4258-90eb-4feb054f3966

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ABANDONADAS até 20s' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] > 10 && GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 20)
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		displayFolder: Telefonia
		lineageTag: 3e33188f-cdfc-447e-9b6b-f968c4667caa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ATENDIDAS até 5s' =
			
			
			VAR ATENDIDAS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <= 5)
			
			RETURN
			
			IF(ATENDIDAS=0, BLANK(), ATENDIDAS)
		displayFolder: Telefonia
		lineageTag: c7d9d2e9-1127-4fcf-8ba3-f380d4362b4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ATENDIDAS até 10s' =
			
			
			VAR ATENDIDAS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] > 5 && GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <=10)
			
			RETURN
			
			IF(ATENDIDAS=0, BLANK(), ATENDIDAS)
		displayFolder: Telefonia
		lineageTag: 6b708130-6c63-4cdc-a038-94d2fd016d8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ATENDIDAS até 20s' =
			
			
			VAR ATENDIDAS = CALCULATE(SUM(GENESYS_FT_ATENDIDAS[ATENDIDAS]),GENESYS_FT_ATENDIDAS[ANSWERED_TIME] > 10 && GENESYS_FT_ATENDIDAS[ANSWERED_TIME] <=20)
			
			RETURN
			
			IF(ATENDIDAS=0, BLANK(), ATENDIDAS)
		displayFolder: Telefonia
		lineageTag: 6cd8389d-6f27-4a60-b912-c6ffa5feaafd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Horário Mais Ligações' = ```
			
			VAR VolumePorIntervalo =
			    SUMMARIZE(
			        '!DIM_CALENDARIO',
			        '!DIM_CALENDARIO'[Intervalo Hora],
			        "TotalRecebidas", 
			        [RECEBIDAS]
			    )
			VAR IntervaloComMaiorVolume = 
			    TOPN(1, VolumePorIntervalo, [TotalRecebidas], DESC)
			RETURN
			    MAXX(IntervaloComMaiorVolume, '!DIM_CALENDARIO'[Intervalo Hora])
			```
		displayFolder: Telefonia
		lineageTag: 5d7c55d8-0925-4368-809a-7887bcf0b2e8

	measure 'Dia da Semana Mais Ligações' = ```
			
			VAR VolumePorIntervalo =
			    SUMMARIZE(
			        '!DIM_CALENDARIO',
			        '!DIM_CALENDARIO'[Dia da Semana],
			        "TotalRecebidas", 
			        [RECEBIDAS]
			    )
			VAR IntervaloComMaiorVolume = 
			    TOPN(1, VolumePorIntervalo, [TotalRecebidas], DESC)
			RETURN
			    MAXX(IntervaloComMaiorVolume, '!DIM_CALENDARIO'[Dia da Semana])
			```
		displayFolder: Telefonia
		lineageTag: 13be6682-6df7-477e-8c1a-ee1158c1f6b9

	measure 'Média Atendidas 2.0' = ```
			
			VAR DiasRelevantes = 
			    FILTER(
			        SUMMARIZE(
			            '!DIM_CALENDARIO',
			            '!DIM_CALENDARIO'[Date],
			            '!DIM_CALENDARIO'[Dia da Semana]
			        ),
			        [RECEBIDAS] > 0
			    )
			RETURN
			DIVIDE(
			    [RECEBIDAS],
			    COUNTROWS(DiasRelevantes),
			    BLANK()
			)
			```
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 332bd0cb-4600-43bb-9b6a-457d48193662

		annotation PBI_FormatHint = {"isDecimal":true}

	measure %REGISTROS = [REGISTROS]/[ATENDIDAS]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Tabulações
		lineageTag: d98f12ac-7752-4d97-8956-84ef785d6d67

	measure REGISTROS = ```
			
			
			
			
			IFERROR(
			    IF(
			        ISBLANK(
			            CALCULATE(
			                COUNTROWS(GENESYS_TABULACOES),
			                NOT(
			                    CONTAINSSTRING(GENESYS_TABULACOES[Sub Motivo], "Muda") || 
			                    GENESYS_TABULACOES[Sub Motivo] = "Teste (Supervisor)" || 
			                    GENESYS_TABULACOES[Razão do Status] = "Cancelado"
			                )
			            )
			        ) = TRUE(),
			        0,
			        CALCULATE(
			            COUNTROWS(GENESYS_TABULACOES),
			            NOT(
			                CONTAINSSTRING(GENESYS_TABULACOES[Sub Motivo], "Muda") || 
			                GENESYS_TABULACOES[Sub Motivo] = "Teste (Supervisor)" || 
			                GENESYS_TABULACOES[Razão do Status] = "Cancelado"
			            )
			        )
			    ),
			    0
			)
			
			```
		formatString: 0
		displayFolder: Tabulações
		lineageTag: efd62ba5-7e68-419d-98d4-ddf480d2fd4e

	measure 'Índice Não Conf. no Atend.' =
			
			VAR Qtd_INA = CALCULATE(COUNT(FT_QUALIDADE_LLM[Status Nota]), FT_QUALIDADE_LLM[Status Nota] <> "Nota Máxima")
			VAR Total_Aval = COUNTROWS(FT_QUALIDADE_LLM)
			
			RETURN
			
			DIVIDE(Qtd_INA,Total_Aval, 0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: 4b921ddf-a09d-4b20-adeb-671b36f77cb3

	measure 'Media Qualidade' = AVERAGE(FT_QUALIDADE_LLM[Nota Final])
		displayFolder: Qualidade
		lineageTag: 93813b3b-bb12-4015-80bb-1e21be02cf4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Qtde Avaliacoes' = COUNTROWS(FT_QUALIDADE_LLM)
		formatString: 0
		displayFolder: Qualidade
		lineageTag: afad7bec-d403-48e4-bb2c-544d70d017a3

	measure 'Qtde NC' = CALCULATE(COUNT(FT_QUALIDADE_LLM[Tipo]), FT_QUALIDADE_LLM[Tipo] = "NC")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 89b5aa67-640c-4444-ad6f-e14d0095299e

	measure 'Qtde NCG' = CALCULATE(COUNT(FT_QUALIDADE_LLM[Tipo]), FT_QUALIDADE_LLM[Tipo] = "NCG")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 48e3de66-a5ed-4f01-8738-bcdb89aac212

	measure 'Qtde Nota Max' = CALCULATE(COUNT(FT_QUALIDADE_LLM[Tipo]), FT_QUALIDADE_LLM[Tipo] = "Nota Máxima")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: a5edb95f-2c78-45a4-b6cd-a2c16b261ea8

	measure 'Média Ating. Blocos de Critérios' = ```
			
			VAR MEDIA_ATING_BLOCOS = (COUNTROWS(FT_QUALIDADE_LLM)-COUNT(FT_OFENSORES_LLM[TAG]))/COUNTROWS(FT_QUALIDADE_LLM)
			
			RETURN
			
			CALCULATE(MEDIA_ATING_BLOCOS,
			    FILTER(FT_OFENSORES_LLM, FT_OFENSORES_LLM[Bloco] = SELECTEDVALUE(FT_OFENSORES_LLM[Bloco]))
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Qualidade
		lineageTag: bfe3c9d4-3756-45bc-81f8-e772aae6eea8

	measure 'Despontuações NC' = CALCULATE(COUNT(FT_OFENSORES_LLM[TAG]), FT_OFENSORES_LLM[NCG] = "Não")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 5467c620-1109-4d9e-8b15-0c9c9fd72f01

	measure 'Despontuações NCG' = CALCULATE(COUNT(FT_OFENSORES_LLM[TAG]), FT_OFENSORES_LLM[NCG] = "Sim")
		formatString: 0
		displayFolder: Qualidade
		lineageTag: cee2569b-b78e-4c2b-a964-9abf729d6f87

	measure 'Total Despontuações' = COUNT(FT_OFENSORES_LLM[TAG])
		formatString: 0
		displayFolder: Qualidade
		lineageTag: 9907350a-f431-42b1-9d21-8d8bc2dc7988

	measure @TMA = 360
		formatString: 0
		displayFolder: Forecast
		lineageTag: cea662c2-9f88-4214-a141-e611c4955aff

	measure @TME = 20
		formatString: 0
		displayFolder: Forecast
		lineageTag: f5a13d66-6370-48dc-8a14-b2284f9b046a

	measure @TA = 0.03
		displayFolder: Forecast
		lineageTag: b07de12b-83e0-4df7-b400-219692666456

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TA = DIVIDE([ABANDONADAS Acima 20s],[RECEBIDAS], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: d2608759-d080-4002-9e14-3d1c175a2fe9

	measure @ABANDONO = 0.05
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Forecast
		lineageTag: 1d870d28-9bc5-4a40-9616-9473dd34c361

	measure IAF =
			
			VAR Desconexoes = SUM('GENESYS_FT_DESCONEXÃO'[Desonexão Agente])
			
			RETURN
			
			IF(Desconexoes = BLANK(), 0, Desconexoes)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 853e2b43-f47e-4761-a831-2ca312fff6be

	measure '% IAF' = IFERROR([IAF]/[RECEBIDAS],0) --% DE DESCONEXÃO
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Telefonia
		lineageTag: e3faeb2c-7ad7-4c1c-99e7-e94861785028

	measure %TME =
			
			
			VAR A = DIVIDE([TME],[@TME],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TME]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 755a8a12-b772-4abb-a0b1-6d0ac8077eb5

	measure %TMA =
			
			
			VAR A = DIVIDE([TMA],[@TMA],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@TMA]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: 6df55d10-7818-437b-916b-90da3916954e

	measure %ABANDONO =
			
			
			VAR A = DIVIDE([%ABANDONADAS],[@ABANDONO],BLANK())-1
			
			RETURN
			
			 SWITCH(TRUE(),
			    ISBLANK([@ABANDONO]), BLANK(),A)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Desvio
		lineageTag: b2a750dc-56f9-4915-9906-2494d1080b16

	measure '% Satisfeitos' = DIVIDE([Qtde. Satisfeitos],[Qtde. Pesquisas],BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 05f4157e-fb18-4359-92ce-9903c8d7127b

	measure '% Insatisfeitos' = [Qtde. Insatisfeitos]/[Qtde. Pesquisas]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 6b4f2217-c06d-43ab-ae45-e4126864dd20

	measure 'Qtde. Satisfeitos' = CALCULATE(COUNT(GENESYS_FT_CSAT[SCORE]), GENESYS_FT_CSAT[SCORE] >=4)
		formatString: 0
		displayFolder: NPS
		lineageTag: ba4cdac9-6b2b-49b2-b149-b1bc5ee9a439

	measure 'Qtde. Insatisfeitos' = CALCULATE(COUNT(GENESYS_FT_CSAT[SCORE]), GENESYS_FT_CSAT[SCORE] <=2)
		formatString: 0
		displayFolder: NPS
		lineageTag: 97d8a7f6-4c88-425d-831e-da37aeba3a02

	measure 'Qtde. Pesquisas' = COUNTROWS(GENESYS_FT_CSAT)
		formatString: 0
		displayFolder: NPS
		lineageTag: 117fd285-8d9c-4302-b56e-f030b52a139c

	measure 'ABANDONADAS até 10s Total' =
			
			
			VAR ABN = CALCULATE(SUM(GENESYS_FT_ABANDONADAS[ABANDONADAS]),GENESYS_FT_ABANDONADAS[ABANDON_TIME] <= 10)
			
			RETURN
			
			IF(ABN=0, BLANK(), ABN)
		formatString: 0
		displayFolder: Telefonia
		lineageTag: 500d0c0e-ed45-4150-9ca4-1bb94cfce60f

	measure @INSATISFACAO = 0.02
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 84d6787b-68b3-4d08-9f3a-bf6c7da8802c

	measure @SATISFACAO = 0.85
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 52110e2c-77ec-483c-a760-9a9d23f3f583

	measure '% Insatisf. Proj.' =
			
			VAR INSATISFEITOS = [% Insatisfeitos]
			VAR META_INSATISFEITOS = [@INSATISFACAO]
			VAR DESVIO_INSATISFEITOS = DIVIDE(INSATISFEITOS, META_INSATISFEITOS, 0)
			
			RETURN
			IF(DESVIO_INSATISFEITOS = 0, 0, DESVIO_INSATISFEITOS - 1)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 4fb30885-2f6e-48f1-96d4-528a9b7085b1

	measure '% Satisf. Proj.' =
			
			VAR SATISFEITOS = [% Satisfeitos]
			VAR META_SATISFEITOS = [@SATISFACAO]
			VAR DESVIO_SATISFEITOS = DIVIDE(SATISFEITOS, META_SATISFEITOS, 0)
			
			RETURN
			IF(DESVIO_SATISFEITOS = 0, 0, DESVIO_SATISFEITOS - 1)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: NPS
		lineageTag: 52207987-1648-49b5-8f59-d320115631b1

	measure 'Ligações Mudas' =
			
			
			var lig_muda = CALCULATE(COUNTROWS(GENESYS_TABULACOES),GENESYS_TABULACOES[Sub Motivo]="Muda")
			
			RETURN
			
			IF(ISBLANK(lig_muda),0,lig_muda)
		formatString: 0
		lineageTag: fca5a802-681c-4cc8-b9c7-7bef9d98b5d1

	measure 'Ligações Teste' = ```
			
			
			
			var lig_muda = CALCULATE(COUNTROWS(GENESYS_TABULACOES),GENESYS_TABULACOES[Sub Motivo] in {"Teste (supervisor)", "Teste Ura", "Teste de ura"})
			
			RETURN
			lig_muda
			
			
			```
		formatString: 0
		lineageTag: a05ae8b4-29ff-4c1c-972a-5c9873d9014b

	measure Tooltip_Analise = ```
			
			VAR Tipo = SELECTEDVALUE(Dim_Tooltip[TooltipID])
			VAR NS = [NS Realizado]
			VAR MetaNS = 0.9
			VAR Abandono = [%ABANDONADAS]
			VAR MetaAbandono = 0.05
			VAR TMO = [TMO]
			VAR MetaTMO = 542
			VAR Recebidas = [RECEBIDAS]
			VAR ForecastRecebidas = [@RECEBIDAS]
			VAR Atendidas = [ATENDIDAS]
			VAR ForecastAtendidas = [@ATENDIDAS]
			VAR PAsLogadas = [ContaPA_Max]
			VAR ForecastPAs = [@PA]
			
			RETURN
			SWITCH(
			    TRUE(),
			
			    -- =========================
			    -- TOOLTIP NS
			    -- =========================
			    Tipo = "NS",
			        IF(
			            ISBLANK(NS),
			            "ℹ️ Nível de Serviço" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            SWITCH(
			                TRUE(),
			
			                NS >= MetaNS,
			                "🟢 Nível de Serviço dentro da meta" & UNICHAR(10) & UNICHAR(10) &
			                "O NS atual está em " & FORMAT(NS, "0.00%") &
			                ", acima da meta de 90,00%." & UNICHAR(10) &
			                "O tempo de espera está adequado para o cliente." & UNICHAR(10) &
			                "Recomendação: manter o dimensionamento atual.",
			
			                NS >= 0.85,
			                "🟡 Nível de Serviço em alerta" & UNICHAR(10) & UNICHAR(10) &
			                "O NS atual está em " & FORMAT(NS, "0.00%") &
			                ", abaixo da meta de 90,00%." & UNICHAR(10) &
			                "Há aumento perceptível no tempo de espera." & UNICHAR(10) &
			                "Recomendação: revisar escala e aderência.",
			
			                "🔴 Nível de Serviço crítico" & UNICHAR(10) & UNICHAR(10) &
			                "O NS atual está em " & FORMAT(NS, "0.00%") &
			                ", muito abaixo da meta de 90,00%." & UNICHAR(10) &
			                "Impacto direto na experiência do cliente." & UNICHAR(10) &
			                "Recomendação: reforçar atendimento imediatamente."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP ABANDONO
			    -- =========================
			    Tipo = "ABANDONO",
			        IF(
			            ISBLANK(Abandono),
			            "ℹ️ Abandono" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            SWITCH(
			                TRUE(),
			
			                Abandono <= MetaAbandono,
			                "🟢 Abandono dentro da meta" & UNICHAR(10) & UNICHAR(10) &
			                "O abandono está em " & FORMAT(Abandono, "0.00%") &
			                ", dentro da meta operacional de até 5,00%." & UNICHAR(10) &
			                "O tempo de espera está adequado e a retenção é satisfatória." & UNICHAR(10) &
			                "Recomendação: manter o dimensionamento atual.",
			
			                Abandono <= 0.08,
			                "🟡 Abandono em nível de atenção" & UNICHAR(10) & UNICHAR(10) &
			                "O abandono está em " & FORMAT(Abandono, "0.00%") &
			                ", acima da meta de 5,00%." & UNICHAR(10) &
			                "Há indícios de aumento no tempo de espera ou filas." & UNICHAR(10) &
			                "Recomendação: revisar picos de demanda e aderência.",
			
			                "🔴 Abandono crítico" & UNICHAR(10) & UNICHAR(10) &
			                "O abandono está em " & FORMAT(Abandono, "0.00%") &
			                ", muito acima da meta de 5,00%." & UNICHAR(10) &
			                "Clientes estão desistindo antes do atendimento." & UNICHAR(10) &
			                "Recomendação: reforçar escala e priorizar filas críticas."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP TMO
			    -- =========================
			    Tipo = "TMO",
			        IF(
			            ISBLANK(TMO),
			            "ℹ️ TMO" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            SWITCH(
			                TRUE(),
			
			                TMO <= MetaTMO,
			                "🟢 TMO dentro da meta" & UNICHAR(10) & UNICHAR(10) &
			                "O TMO está em " & FORMAT(TMO, "0") &
			                ", dentro da meta operacional de até " & MetaTMO & "." & UNICHAR(10) &
			                "O TMO está controlado e compatível com o forecast." & UNICHAR(10) &
			                "Recomendação: manter a eficiência e qualidade.",
			
			                TMO <= MetaTMO * 1.1,
			                "🟡 TMO em nível de atenção" & UNICHAR(10) & UNICHAR(10) &
			                "O TMO está em " & FORMAT(TMO, "0") &
			                ", acima da meta de " & MetaTMO & "." & UNICHAR(10) &
			                "Pode indicar dificuldade operacional ou falhas de script." & UNICHAR(10) &
			                "Recomendação: Monitorar causas.",
			
			                "🔴 TMO crítico" & UNICHAR(10) & UNICHAR(10) &
			                "O TMO está em " & FORMAT(TMO, "0") &
			                ", muito acima da meta de " & MetaTMO & "." & UNICHAR(10) &
			                "Impacto no NS e no Abandono." & UNICHAR(10) &
			                "Recomendação: Revisar processos, scripts, sistemas e capacitação."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP VOLUME RECEBIDO
			    -- =========================
			    Tipo = "VOLUME_RECEBIDO",
			        IF(
			            ISBLANK(Recebidas),
			            "ℹ️ Volume Recebido" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            "📞 Volume Recebido" & UNICHAR(10) & UNICHAR(10) &
			            "Foram recebidas " & FORMAT(Recebidas, "0") & " chamadas no período." & UNICHAR(10) &
			            "O impacto operacional depende da capacidade disponível." & UNICHAR(10) &
			            "Recomendação: analisar em conjunto com NS, Abandono e PAs logadas."
			        ),
			
			    -- =========================
			    -- TOOLTIP VOLUME ATENDIDO
			    -- =========================
			    Tipo = "VOLUME_ATENDIDO",
			        IF(
			            ISBLANK(Atendidas),
			            "ℹ️ Volume Atendido" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            VAR TaxaAtendimento = DIVIDE(Atendidas, Recebidas)
			
			            RETURN
			            SWITCH(
			                TRUE(),
			
			                TaxaAtendimento >= 0.95,
			                "🟢 Volume Atendido adequado" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(Atendidas, "0") & " chamadas atendidas." & UNICHAR(10) &
			                "Alta taxa de absorção da demanda." & UNICHAR(10) &
			                "Recomendação: manter capacidade atual.",
			
			                TaxaAtendimento >= 0.90,
			                "🟡 Volume Atendido em atenção" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(Atendidas, "0") & " chamadas atendidas." & UNICHAR(10) &
			                "Parte da demanda não está sendo absorvida." & UNICHAR(10) &
			                "Recomendação: revisar escala e TMO.",
			
			                "🔴 Volume Atendido crítico" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(Atendidas, "0") & " chamadas atendidas." & UNICHAR(10) &
			                "Baixa capacidade frente à demanda." & UNICHAR(10) &
			                "Recomendação: reforçar PAs e reduzir tempo médio."
			            )
			        ),
			
			    -- =========================
			    -- TOOLTIP PAs LOGADAS
			    -- =========================
			    Tipo = "PAS",
			        IF(
			            ISBLANK(PAsLogadas),
			            "ℹ️ PAs Logadas" & UNICHAR(10) &
			            "Sem dados suficientes para avaliação no período.",
			
			            VAR AderenciaPA = DIVIDE(PAsLogadas, ForecastPAs)
			
			            RETURN
			            SWITCH(
			                TRUE(),
			
			                AderenciaPA >= 0.95,
			                "🟢 PAs dentro do planejado" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(PAsLogadas, "0") & " PAs logadas." & UNICHAR(10) &
			                "A escala está sendo cumprida adequadamente." & UNICHAR(10) &
			                "Recomendação: manter gestão atual.",
			
			                AderenciaPA >= 0.85,
			                "🟡 PAs em nível de atenção" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(PAsLogadas, "0") & " PAs logadas." & UNICHAR(10) &
			                "Déficit parcial de operadores." & UNICHAR(10) &
			                "Recomendação: verificar faltas, pausas e aderência.",
			
			                "🔴 PAs críticas" & UNICHAR(10) & UNICHAR(10) &
			                FORMAT(PAsLogadas, "0") & " PAs logadas." & UNICHAR(10) &
			                "Déficit severo de capacidade operacional." & UNICHAR(10) &
			                "Recomendação: acionar contingência e replanejar escala."
			            )
			        ),
			 
			
			    -- FALLBACK
			    "ℹ️ Indicador não identificado"
			)
			
			```
		displayFolder: INTELIGENTE
		lineageTag: 5f692491-75a6-4239-a4f7-e94b8e6a1337

	column Column
		isHidden
		formatString: 0
		lineageTag: e4da24e7-a23d-4f89-83e6-e5f62f6f1205
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition !Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 3e1c8ff410e1421897d7da13d3b8f2c3

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

