table DIM_DATAS
	lineageTag: 6dff3d23-5cc8-4439-a44c-50ef251554fb

	column funcional
		dataType: string
		lineageTag: dc740452-861a-4ac2-8e89-e1ed5112721f
		summarizeBy: none
		sourceColumn: funcional

		annotation SummarizationSetBy = Automatic

	column dtInício
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3a6173f6-6a4a-46b6-937a-2dda8f316206
		summarizeBy: none
		sourceColumn: dtInício

		variation Variation
			isDefault
			relationship: 1d1e9c71-e8d5-4cf9-aa45-98b4ee822a73
			defaultHierarchy: LocalDateTable_deea2cd9-3728-47f5-b63c-ed7a6d262abf.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dtRecente
		dataType: dateTime
		formatString: Short Date
		lineageTag: bea9fa5c-849f-44ff-a16f-af42a5929847
		summarizeBy: none
		sourceColumn: dtRecente

		variation Variation
			isDefault
			relationship: f5bf3848-3efc-44f4-b868-659ed5b4d210
			defaultHierarchy: LocalDateTable_db50f504-ab2d-48b3-9fce-b8560055bc71.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DIM_DATAS = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Fonte = PowerBI.Dataflows([]),
				    #"cd285858-e86a-4854-ae7f-7fbf647a6920" = Fonte{[workspaceId="cd285858-e86a-4854-ae7f-7fbf647a6920"]}[Data],
				    #"46015645-f474-46ff-bce3-145062ef6197" = #"cd285858-e86a-4854-ae7f-7fbf647a6920"{[dataflowId="46015645-f474-46ff-bce3-145062ef6197"]}[Data],
				    Dim_dtinicio_dtfim = #"46015645-f474-46ff-bce3-145062ef6197"{[entity="Dim_dtinicio_dtfim"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(Dim_dtinicio_dtfim, each ([produto] = "SULGAS")),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"Func", "funcional"}}),
				    #"Linhas Agrupadas1" = Table.Group(#"Colunas Renomeadas", {"funcional"}, {{"dtInício", each List.Min([dtInício]), type nullable date}, {"dtRecente", each List.Max([dtRecente]), type nullable date}})
				in
				    #"Linhas Agrupadas1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

