table FT_OFENSORES_LLM
	lineageTag: 50043492-1ad7-42c8-acbc-70619a84142d

	column 'Nome da Origem'
		dataType: string
		lineageTag: 977dda00-dd28-40e8-b29d-af2b57163f4d
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column Protocolo
		dataType: string
		lineageTag: 98f45f51-6dfb-428d-a4d1-cf9a74cbc8e3
		summarizeBy: none
		sourceColumn: Protocolo

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: e296a4dc-fef4-458a-8191-02a92574f098
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Bloco
		dataType: string
		lineageTag: 7d621be4-fb4a-4137-8970-5dabf96e2a0d
		summarizeBy: none
		sourceColumn: Bloco

		annotation SummarizationSetBy = Automatic

	column TAG
		dataType: string
		lineageTag: c54dbdd6-4baa-4629-8627-a1675ae8c405
		summarizeBy: none
		sourceColumn: TAG

		annotation SummarizationSetBy = Automatic

	column Sub-Item
		dataType: string
		lineageTag: 676be87d-997d-45d3-bee2-36d10ba30b9d
		summarizeBy: none
		sourceColumn: Sub-Item

		annotation SummarizationSetBy = Automatic

	column NCG
		dataType: string
		lineageTag: b43aef74-b6cb-40ac-8b9d-970507d17ded
		summarizeBy: none
		sourceColumn: NCG

		annotation SummarizationSetBy = Automatic

	column Diagnóstico
		dataType: string
		lineageTag: e42ba93f-05c8-4ce5-9c6e-9036db60aeb0
		summarizeBy: none
		sourceColumn: Diagnóstico

		annotation SummarizationSetBy = Automatic

	column Peso
		dataType: double
		lineageTag: 88e10038-b92b-4082-ae2c-df5ef8d02e4a
		summarizeBy: sum
		sourceColumn: Peso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Apontamento
		dataType: string
		lineageTag: 19cd04b4-1f63-4fed-a44e-5ebc0a86dadd
		summarizeBy: none
		sourceColumn: Apontamento

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 1aacf7b8-f54e-464c-9166-d8d8e672545b
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: bda5dcf3-25a3-4c19-a9d0-75bcf755e5ba
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	partition FT_OFENSORES_LLM = m
		mode: import
		source = ```
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"cd285858-e86a-4854-ae7f-7fbf647a6920" = Workspaces{[workspaceId="cd285858-e86a-4854-ae7f-7fbf647a6920"]}[Data],
				    #"287e2c31-79b7-4f71-8901-c2df7db09ddc" = #"cd285858-e86a-4854-ae7f-7fbf647a6920"{[dataflowId="287e2c31-79b7-4f71-8901-c2df7db09ddc"]}[Data],
				    #"Ft_Apontamentos LLM_" = #"287e2c31-79b7-4f71-8901-c2df7db09ddc"{[entity="Ft_Apontamentos LLM",version=""]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(#"Ft_Apontamentos LLM_", each Text.Contains([Cliente], "SULGÁS") or Text.Contains([Cliente], "Sulgás")),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"Name", "Nome da Origem"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Peso", type number}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Cliente", "Monitorado", "Supervisor", "Nome da Ficha"}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"Nome da Origem", "TAG", "Item", "Apontamento"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Reordenadas", "Item 2", each if Text.StartsWith([Item], "1.") or Text.StartsWith([Item], "2.") or Text.StartsWith([Item], "3.") then 
				    Text.Middle([Item], 4) 
				else 
				    [Item]),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Personalização Adicionada",{"Item"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"Item 2", "Item"}}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Item", type text}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Tipo Alterado2", "Índice", 1, 1, Int64.Type),
				    #"Texto Aparado" = Table.TransformColumns(#"Índice Adicionado",{{"Item", Text.Trim, type text}})
				in
				    #"Texto Aparado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

