table FT_QUALIDADE_LLM
	lineageTag: 67bcdc71-7061-4c0b-a529-52004a18eab9

	column Name
		dataType: string
		lineageTag: f3a9517e-314d-42b3-817c-b1b322096a59
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Nome do Formulário'
		dataType: string
		lineageTag: 128dc88b-32d8-4685-8673-2706544bd052
		summarizeBy: none
		sourceColumn: Nome do Formulário

		annotation SummarizationSetBy = Automatic

	column Agente
		dataType: string
		lineageTag: f2c4078f-d562-4887-8fd3-563b7eb53824
		summarizeBy: none
		sourceColumn: Agente

		annotation SummarizationSetBy = Automatic

	column Funcional
		dataType: string
		lineageTag: 087f4c14-846a-4175-ac58-5ddeda45cd2d
		summarizeBy: none
		sourceColumn: Funcional

		annotation SummarizationSetBy = Automatic

	column Supervisor
		dataType: string
		lineageTag: 4b43a6e4-f724-4ba7-b76c-73c943e77154
		summarizeBy: none
		sourceColumn: Supervisor

		annotation SummarizationSetBy = Automatic

	column 'Data da Avaliação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f30579a-e84a-4990-ae46-58ad298558ec
		summarizeBy: none
		sourceColumn: Data da Avaliação

		variation Variation
			isDefault
			relationship: c7a37547-d738-411c-8b07-fb0129f19e21
			defaultHierarchy: LocalDateTable_28d56ee8-f190-4a7d-9f6e-cb6c1695bd7f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tempo de Avaliação'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5b30b125-f450-4bcc-9e81-19b0e152e8d6
		summarizeBy: none
		sourceColumn: Tempo de Avaliação

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Data do contato'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2b951506-acbd-43ce-9f97-18938e6d9dc5
		summarizeBy: none
		sourceColumn: Data do contato

		variation Variation
			isDefault
			relationship: 83185343-a80c-46a8-b228-0dd9638a84cd
			defaultHierarchy: LocalDateTable_d3434e35-b4fc-480e-bc8a-90d49832086c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Duração
		dataType: string
		lineageTag: 2d0c00f2-3255-460d-a3ba-4fd84bd74afa
		summarizeBy: none
		sourceColumn: Duração

		annotation SummarizationSetBy = Automatic

	column Protocolo
		dataType: string
		lineageTag: 9c073cfa-fa62-441c-a50c-7844a689f1e2
		summarizeBy: none
		sourceColumn: Protocolo

		annotation SummarizationSetBy = Automatic

	column Monitor
		dataType: string
		lineageTag: aa4857c5-69b5-43de-a8d3-9913dca32f95
		summarizeBy: none
		sourceColumn: Monitor

		annotation SummarizationSetBy = Automatic

	column Improdutivo
		dataType: string
		lineageTag: c34a4d6e-f177-44eb-a365-7b8d0fdaf3f6
		summarizeBy: none
		sourceColumn: Improdutivo

		annotation SummarizationSetBy = Automatic

	column TAG
		dataType: string
		lineageTag: b95632d8-75fb-45c0-a8d2-b62f66c323ea
		summarizeBy: none
		sourceColumn: TAG

		annotation SummarizationSetBy = Automatic

	column 'Nota Inicial'
		dataType: double
		lineageTag: 1d5421de-8167-4340-889d-8be4b691d28c
		summarizeBy: sum
		sourceColumn: Nota Inicial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nota Final'
		dataType: double
		lineageTag: 0ec4659f-e32a-4e81-9acd-a543a77c3f64
		summarizeBy: sum
		sourceColumn: Nota Final

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tipo da avaliação:'
		dataType: string
		lineageTag: d3775f48-e040-48a8-bfb0-f3748f9c0445
		summarizeBy: none
		sourceColumn: Tipo da avaliação:

		annotation SummarizationSetBy = Automatic

	column Feedback
		dataType: string
		lineageTag: 131cda74-af14-40a0-8e2d-706f760e7380
		summarizeBy: none
		sourceColumn: Feedback

		annotation SummarizationSetBy = Automatic

	column 'Data do feedback'
		dataType: dateTime
		formatString: General Date
		lineageTag: fd314d35-de2f-4fd1-8fba-9b72734fb491
		summarizeBy: none
		sourceColumn: Data do feedback

		variation Variation
			isDefault
			relationship: a4f447a4-8f01-44e0-a0c4-76f30e5c2847
			defaultHierarchy: LocalDateTable_f5f63eab-3553-4f18-87ff-fec3cd88c47d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Quem aplicou feedback'
		dataType: string
		lineageTag: 4d65a606-4a53-4e17-950b-647da850ef86
		summarizeBy: none
		sourceColumn: Quem aplicou feedback

		annotation SummarizationSetBy = Automatic

	column 'Data da Contestação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 211c1e8d-4013-4565-8894-dfd8dbcd13e0
		summarizeBy: none
		sourceColumn: Data da Contestação

		variation Variation
			isDefault
			relationship: 45f64c2c-ee69-4fce-aa98-f5da3f0b9c41
			defaultHierarchy: LocalDateTable_5fedb0b9-6fb0-461a-a007-82af49c2d0c7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Quem contestou'
		dataType: string
		lineageTag: e30e046c-07f1-4ab6-bcf0-7dfeac121ef8
		summarizeBy: none
		sourceColumn: Quem contestou

		annotation SummarizationSetBy = Automatic

	column Comentário
		dataType: string
		lineageTag: dff4d2c4-97d2-4826-bebb-40f6443578d2
		summarizeBy: none
		sourceColumn: Comentário

		annotation SummarizationSetBy = Automatic

	column 'Resumo do contato'
		dataType: string
		lineageTag: 57394036-6027-4343-9b71-57341ab849b9
		summarizeBy: none
		sourceColumn: Resumo do contato

		annotation SummarizationSetBy = Automatic

	column Empresa:
		dataType: string
		lineageTag: de405566-826a-45d5-a90a-fe2a3e371013
		summarizeBy: none
		sourceColumn: Empresa:

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: c669e061-a294-4446-8e35-2aa0eb07ec52
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Avaliador
		dataType: string
		lineageTag: 696f6093-2369-4894-a80e-8b809548c697
		summarizeBy: none
		sourceColumn: Avaliador

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 243f226a-a9b2-4680-8ab5-f0fe7ba270e2
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column Tempo
		dataType: double
		lineageTag: 5bdb4ab2-b3aa-4211-9d49-b80e44baf54a
		summarizeBy: sum
		sourceColumn: Tempo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tempo Limite'
		dataType: dateTime
		formatString: General Date
		lineageTag: 570d7ad8-c311-4237-a986-5f92a200057c
		summarizeBy: none
		sourceColumn: Tempo Limite

		variation Variation
			isDefault
			relationship: 0c2742d1-880b-4ccb-9705-95f6be1fd399
			defaultHierarchy: LocalDateTable_e47e17d4-b2f9-4e55-b0c5-e1db8a732620.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Status Feedback'
		dataType: string
		lineageTag: cddb5896-f5fe-4501-8c79-51aeb4249efb
		summarizeBy: none
		sourceColumn: Status Feedback

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Nota'
		dataType: string
		lineageTag: 76829036-1d41-4b27-b7ec-e43317aaf8a4
		summarizeBy: none
		sourceColumn: Tipo de Nota

		annotation SummarizationSetBy = Automatic

	column 'Status Nota'
		dataType: string
		lineageTag: 0e052053-d4ea-44cc-8f52-97dcfaab3860
		summarizeBy: none
		sourceColumn: Status Nota

		annotation SummarizationSetBy = Automatic

	column 'Tempo na Sulgas (d)' = TODAY()-RELATED(DIM_DATAS[dtInício])
		dataType: int64
		formatString: 0
		lineageTag: 27b2e9a5-f382-48bf-a9be-ff15bed6408f
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Senioridade = IF((TODAY()-RELATED(DIM_DATAS[dtInício]))>30,"Veterano","Novato")
		lineageTag: f64c1d21-64ca-4957-b324-eabebe090319
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Data = FORMAT(FT_QUALIDADE_LLM[Data da Avaliação], "DD/MM/YYYY")
		lineageTag: 1ee6fdbe-c012-432e-bdda-1743659e9e71
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TMA
		dataType: string
		lineageTag: 5329d893-9e98-4734-aa89-7069638bd4b1
		summarizeBy: none
		sourceColumn: TMA

		annotation SummarizationSetBy = Automatic

	partition FT_QUALIDADE_LLM = m
		mode: import
		source = ```
				let
				    Fonte = PowerPlatform.Dataflows([]),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"cd285858-e86a-4854-ae7f-7fbf647a6920" = Workspaces{[workspaceId="cd285858-e86a-4854-ae7f-7fbf647a6920"]}[Data],
				    #"aabc750c-e78b-4117-991d-304193bcebde" = #"cd285858-e86a-4854-ae7f-7fbf647a6920"{[dataflowId="aabc750c-e78b-4117-991d-304193bcebde"]}[Data],
				    #"Ft_Qualidade LLM_" = #"aabc750c-e78b-4117-991d-304193bcebde"{[entity="Ft_Qualidade LLM",version=""]}[Data],
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Ft_Qualidade LLM_",{"Arquivo de Origem", "Perfil Avaliador", "Nome da Operação"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas1",{{"Data do Feedback", "Data do feedback"}, {"Quem Contestou", "Quem contestou"}, {"Comentários", "Comentário"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Tipo de Formulário", type text}, {"Nome do Formulário", type text}, {"Status", type text}, {"Agente", type text}, {"Supervisor", type text}, {"Data da Avaliação", type datetime}, {"Tempo de Avaliação", type time}, {"Data do contato", type datetime}, {"Monitor", type text}, {"Improdutivo", type text}, {"TAG", type text}, {"Nota Inicial", type number}, {"Nota Final", type number}, {"Feedback", type text}, {"Data do feedback", type datetime}, {"Quem aplicou feedback", type text}, {"Data da Contestação", type datetime}, {"Quem contestou", type text}, {"Comentário", type any}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each ([Tipo de Formulário] = "Qualidade")),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Filtradas1", each ([Status] <> "Aguardando Análise pelo Avaliador" and [Status] <> "Aguardando Análise pelo Monitor")),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Linhas Filtradas","Qualidade","Monitoria",Replacer.ReplaceText,{"Tipo de Formulário"}),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Valor Substituído1", each Text.Contains([Nome do Formulário], "SULGÁS") or Text.Contains([Nome do Formulário], "Sulgás")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas2",{"Status", "Editada por"}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Colunas Removidas",{{"Monitor", Text.Upper, type text}, {"Agente", Text.Upper, type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Texto em Maiúscula",{{"Tipo de Formulário", "Tipo da avaliação:"}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Renomeadas",{"Nome do Formulário",
				"Agente",
				"Supervisor",
				"Data da Avaliação",
				"Tempo de Avaliação",
				"Data do contato",
				"Duração",
				"Monitor",
				"Improdutivo",
				"TAG",
				"Nota Inicial",
				"Nota Final",
				"Tipo da avaliação:",
				"Feedback",
				"Data do feedback",
				"Quem aplicou feedback",
				"Data da Contestação",
				"Quem contestou"
				}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Reordenadas", "Resumo do contato", each ""),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Empresa:", each "Necxt"),
				    #"Nota Final / 100" = Table.TransformColumns(#"Personalização Adicionada1", {{"Nota Final", each _ / 100, type number}}),
				    #"Nota Inicial / 100" = Table.TransformColumns(#"Nota Final / 100", {{"Nota Inicial", each _ / 100, type number}}),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Nota Inicial / 100", "Agente", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Agente", "Funcional"}),
				    #"Coluna Tipo de Nota" = Table.AddColumn(#"Dividir Coluna por Delimitador", "Tipo", each if [Nota Final] = 100 then "Nota Máxima" else if [Nota Final] >= 1 then "NC" else "NCG"),
				    #"Texto Aparado" = Table.TransformColumns(#"Coluna Tipo de Nota",{{"Agente", Text.Trim, type text}, {"Funcional", Text.Trim, type text}}),
				    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Texto Aparado", {{"Agente", each Text.BeforeDelimiter(_, " - "), type text}}),
				    #"Cira coluna Avaliador" = Table.AddColumn(#"Texto Extraído Antes do Delimitador", "Avaliador", each if Text.Contains([Monitor], "MONITOR AUDITOR") then "Auditor" else if Text.Contains([Monitor], "MONITOR") then "Monitor" else "Supervisor"),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Cira coluna Avaliador", "Nome do Dia", each Date.DayOfWeekName([Data da Avaliação]), type text),
				    #"Personalização Adicionada0" = Table.AddColumn(#"Nome do Dia Inserido", "Tempo", each if [Nome do Dia]="quinta-feira" and [Tipo]="NCG" 
				then 1
				else if [Nome do Dia]="quinta-feira" and [Tipo]="NC" or [Nome do Dia]="quinta-feira" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="quarta-feira" and [Tipo]="NCG" 
				then 1
				else if [Nome do Dia]="quarta-feira" and [Tipo]="NC" or [Nome do Dia]="quarta-feira" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="sexta-feira" and [Tipo]="NCG" 
				then 3
				else if [Nome do Dia]="sexta-feira" and [Tipo]="NC" or [Nome do Dia]="sexta-feira" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="sábado" and [Tipo]="NCG" 
				then 3
				else if [Nome do Dia]="sábado" and [Tipo]="NC" or [Nome do Dia]="sábado" and [Tipo]="Nota Máxima" 
				then 5
				
				else if [Nome do Dia]="domingo" and [Tipo]="NCG" 
				then 2
				else if [Nome do Dia]="domingo" and [Tipo]="NC" or [Nome do Dia]="domingo" and [Tipo]="Nota Máxima" 
				then 4
				
				else if [Tipo]="NCG" 
				then 1
				else if [Tipo]="NC" or [Tipo]="Nota Máxima" 
				then 3
				else "-"),
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada0",{{"Tempo", type duration}, {"Data do feedback", type datetime}}),
				    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Tipo Alterado3", {{"Data do feedback", null}}),
				    #"Cria Coluna Tempo Limite Feed." = Table.AddColumn(#"Erros Substituídos", "Tempo Limite", each [Data da Avaliação]+[Tempo]),
				    #"Cria Coluna Status Feedback" = Table.AddColumn(#"Cria Coluna Tempo Limite Feed.", "Status Feedback", each if [Feedback] = "autofeedback" and [Data do feedback] = null and [Nota Final] = 100 then "Aplicado - Auto Feedback"
				else if [Data do feedback] = null and [Nota Final] = 100 and DateTime.LocalNow() > [Tempo Limite] then "Não Aplicado - Auto Feedback"
				else if [Data do feedback] <> null and [Data do feedback] <= [Tempo Limite] then "Aplicado - Dentro Do Prazo"
				else if [Data do feedback] <> null and [Data do feedback] > [Tempo Limite] then "Aplicado - Fora Do Prazo"
				else if [Data do feedback] = null and DateTime.LocalNow() <= [Tempo Limite] then "Não Aplicado - Dentro do Prazo"
				else if [Data do feedback] = null and DateTime.LocalNow() > [Tempo Limite] then "Não Aplicado"
				else null),
				    #"Cria Coluna Tipo Nota" = Table.AddColumn(#"Cria Coluna Status Feedback", "Tipo de Nota", each if [Nota Final] = 100 then "Nota Maxima" else if [Nota Final] = 0 then "Gravissimo" else "Alerta"),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Cria Coluna Tipo Nota", "Status Nota", each if [Nota Final] = 0 then "NCG" else if [Nota Final] = 100 then "Nota Máxima" else "NC"),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"Status Feedback", type text}, {"Tipo de Nota", type text}, {"Status Nota", type text}, {"Tempo Limite", type datetime}, {"Avaliador", type text}, {"Tipo", type text}, {"Empresa:", type text}, {"Resumo do contato", type text}, {"Comentário", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado5", {"TAG"})
				in
				    #"Duplicatas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

