table GENESYS_TABULACOES
	lineageTag: 918ed5a5-c77a-449a-9472-083839d835a7

	column CHAVE_DATA = FORMAT(GENESYS_TABULACOES[Data de Criação], "DD/MM/YYYY") & " 00:00:00"
		lineageTag: 3c417dfe-1f2d-4dc9-97c2-368aea2d126d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Motivo
		dataType: string
		lineageTag: 0074e29b-a798-46ba-87ef-549ec12a685f
		summarizeBy: none
		sourceColumn: Motivo

		annotation SummarizationSetBy = Automatic

	column 'Sub Motivo'
		dataType: string
		lineageTag: 6e132374-3f39-4831-8269-0861e5d6f7cb
		summarizeBy: none
		sourceColumn: Sub Motivo

		annotation SummarizationSetBy = Automatic

	column 'Número do Protocolo'
		dataType: string
		lineageTag: ac4d5071-fd20-40eb-bf84-891764cbca8f
		summarizeBy: none
		sourceColumn: Número do Protocolo

		annotation SummarizationSetBy = Automatic

	column 'Nome Completo'
		dataType: string
		lineageTag: c066bea3-5d03-4c69-bda7-39678492a560
		summarizeBy: none
		sourceColumn: Nome Completo

		annotation SummarizationSetBy = Automatic

	column 'Cliente / Razão Social'
		dataType: string
		lineageTag: 0044d240-9071-4591-a024-e0e5f3d2619a
		summarizeBy: none
		sourceColumn: Cliente / Razão Social

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Contato'
		dataType: string
		lineageTag: e062bab4-68e0-46fb-8eed-6d108da32d92
		summarizeBy: none
		sourceColumn: Tipo de Contato

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: fc5550e8-9185-4f81-854b-244cb7bee8da
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column 'Razão do Status'
		dataType: string
		lineageTag: c08ba22a-d7d3-4af7-9684-382aa37e7b11
		summarizeBy: none
		sourceColumn: Razão do Status

		annotation SummarizationSetBy = Automatic

	column Proprietário
		dataType: string
		lineageTag: 32b348e2-2605-4be9-a8c4-448137322588
		summarizeBy: none
		sourceColumn: Proprietário

		annotation SummarizationSetBy = Automatic

	column 'Canal de Origem'
		dataType: string
		lineageTag: f70f084e-c60d-4c88-8d5b-5b859f7fdbc3
		summarizeBy: none
		sourceColumn: Canal de Origem

		annotation SummarizationSetBy = Automatic

	column 'Data de Criação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4d49091a-e467-4f96-95ba-b582f0fae2b0
		summarizeBy: none
		sourceColumn: Data de Criação

		variation Variation
			isDefault
			relationship: 62f11b58-a560-43f4-8b08-e6da8628551c
			defaultHierarchy: LocalDateTable_74368aca-9f8b-400e-a98a-a1c9c22eb4a0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Protocolo Importado?'
		dataType: string
		lineageTag: 7c5d6ac0-2e89-444d-ad2f-fb3a1f72c609
		summarizeBy: none
		sourceColumn: Protocolo Importado?

		annotation SummarizationSetBy = Automatic

	column 'Ligação teste' = ```
			
			
			SWITCH(TRUE(),
			GENESYS_TABULACOES[Sub Motivo] in {"Teste (supervisor)", "Teste Ura", "Teste de ura"},1,0)
			
			```
		formatString: 0
		lineageTag: a8534f42-9ba4-4286-92c0-ca5a36021b9a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition GENESYS_TABULACOES = m
		mode: import
		source =
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"d2c83e6d-8ce9-4992-9519-7adb4eca4ce6" = Workspaces{[workspaceId="d2c83e6d-8ce9-4992-9519-7adb4eca4ce6"]}[Data],
				    #"e34a04f7-24ad-4d63-8b82-ed8f7a162ecd" = #"d2c83e6d-8ce9-4992-9519-7adb4eca4ce6"{[dataflowId="e34a04f7-24ad-4d63-8b82-ed8f7a162ecd"]}[Data],
				    Ft_Registros_ = #"e34a04f7-24ad-4d63-8b82-ed8f7a162ecd"{[entity="Ft_Registros",version=""]}[Data],
				
				
				 #"Linhas em Branco Removidas" = Table.SelectRows(#"Ft_Registros_", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

