table GENESYS_FT_CSAT
	lineageTag: 5047818e-de4f-422a-842f-98ad8df3cce0

	column row_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 844cf3cb-de68-443c-93c1-80df909eafff
		summarizeBy: none
		sourceColumn: row_date

		variation Variation
			isDefault
			relationship: f5fb69a0-0e36-469a-8010-f3649bbd8980
			defaultHierarchy: LocalDateTable_6e340a91-755b-49aa-b609-34a20d99d3f6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DIVISION_NAME
		dataType: string
		lineageTag: cd709c9b-b381-4f08-812b-62eb4f25744f
		summarizeBy: none
		sourceColumn: DIVISION_NAME

		annotation SummarizationSetBy = Automatic

	column ROUTING_SKILL_NAME
		dataType: string
		lineageTag: 6c8394db-e314-4a99-a783-0fa1609e001d
		summarizeBy: none
		sourceColumn: ROUTING_SKILL_NAME

		annotation SummarizationSetBy = Automatic

	column CONVERSATION_ID
		dataType: string
		lineageTag: 7fb47988-611a-4850-b5b6-b3fb639281dc
		summarizeBy: none
		sourceColumn: CONVERSATION_ID

		annotation SummarizationSetBy = Automatic

	column RESOURCE_NAME
		dataType: string
		lineageTag: 546242cd-d307-4054-acad-756d5f8dd611
		summarizeBy: none
		sourceColumn: RESOURCE_NAME

		annotation SummarizationSetBy = Automatic

	column EMPLOYEE_ID
		dataType: string
		lineageTag: 8c7b378a-23b6-41f1-91e9-2da5d5072466
		summarizeBy: none
		sourceColumn: EMPLOYEE_ID

		annotation SummarizationSetBy = Automatic

	column TEXT
		dataType: string
		lineageTag: 21377b94-355b-46ce-8b8e-8f0ba1149f3e
		summarizeBy: none
		sourceColumn: TEXT

		annotation SummarizationSetBy = Automatic

	column SCORE
		dataType: int64
		formatString: 0
		lineageTag: 8df58ff4-fad3-4012-b204-8d94c66fd910
		summarizeBy: sum
		sourceColumn: SCORE

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column CONVERSATION_START
		dataType: dateTime
		formatString: General Date
		lineageTag: 70a89103-c9c5-41e8-b629-c6fd634c1f31
		summarizeBy: none
		sourceColumn: CONVERSATION_START

		variation Variation
			isDefault
			relationship: 01497d23-da1d-4427-b0a3-340ad849b93d
			defaultHierarchy: LocalDateTable_e518dd57-0251-49c6-96d4-9909dfa2417b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ANSWER
		dataType: string
		lineageTag: 549b28ae-44af-4ee4-b892-cfb9aaf526a0
		summarizeBy: none
		sourceColumn: ANSWER

		annotation SummarizationSetBy = Automatic

	column CHAVE_DATA = FORMAT(GENESYS_FT_CSAT[row_date], "DD/MM/YYYY HH:MM:SS")
		lineageTag: 1612657c-5c7f-41a1-a74f-a95447c80110
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column USER_NAME
		dataType: string
		lineageTag: bae49b14-2ac4-48b4-be07-977fedbcacf0
		summarizeBy: none
		sourceColumn: USER_NAME

		annotation SummarizationSetBy = Automatic

	column FILA
		dataType: string
		lineageTag: f49fb111-9863-4190-8ff6-7c4305120e0d
		summarizeBy: none
		sourceColumn: FILA

		annotation SummarizationSetBy = Automatic

	column KEYNAME
		dataType: string
		lineageTag: 552c55f3-e88c-46c6-ab33-8ecc7bb438a1
		summarizeBy: none
		sourceColumn: KEYNAME

		annotation SummarizationSetBy = Automatic

	column VALUE
		dataType: string
		lineageTag: ff3f181d-f69e-48c3-8a2e-b95ee3e1fc57
		summarizeBy: none
		sourceColumn: VALUE

		annotation SummarizationSetBy = Automatic

	partition GENESYS_FT_CSAT = m
		mode: import
		source =
				let
				    Fonte = PowerPlatform.Dataflows(null),
				    Workspaces = Fonte{[Id="Workspaces"]}[Data],
				    #"9099524d-5d03-49b4-b51f-776c29c149aa" = Workspaces{[workspaceId="9099524d-5d03-49b4-b51f-776c29c149aa"]}[Data],
				    #"dbbffec5-02b7-401a-bc45-ad720e259ed7" = #"9099524d-5d03-49b4-b51f-776c29c149aa"{[dataflowId="dbbffec5-02b7-401a-bc45-ad720e259ed7"]}[Data],
				    #"GENESYS_CSAT (COMPAGAS)_" = #"dbbffec5-02b7-401a-bc45-ad720e259ed7"{[entity="GENESYS_CSAT (SULGAS)",version=""]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"GENESYS_CSAT (COMPAGAS)_",{{"CONVERSATION_START", type datetime}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each [CONVERSATION_START] >= #"DATA INICIO GENESYS"),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas Filtradas", {"CONVERSATION_ID"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Duplicatas Removidas",{"TOTAL_SCORE", "NPS_SCORE", "INTERVALO"}),
				    #"Linhas Classificadas" = Table.Sort(#"Colunas Removidas",{{"row_date", Order.Descending}})
				in
				    #"Linhas Classificadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

